// Generated by scripts/print-listing-options.ts — do not edit by hand.
// Regenerate with:
//   node -r ts-node/register/transpile-only -r tsconfig-paths/register \
//     scripts/print-listing-options.ts --typescript

export interface ListingOption {
    value: string;
    en: string;
    no: string;
}

/**
 * category — Sent capitalised on a listing. The filter endpoints take the lower-case slug instead —
 * see `CATEGORY_FILTER_SLUGS`.
 */
export const PRODUCT_CATEGORY_OPTIONS = [
    { value: 'Car', en: "Car", no: "Bil" },
    { value: 'Property', en: "Property", no: "Eiendom" },
    { value: 'Boat', en: "Boat", no: "Båt" },
    { value: 'Motorcycle', en: "Motorcycle", no: "MC" },
    { value: 'Bike', en: "Bike", no: "Sykkel" },
    { value: 'Job', en: "Job", no: "Jobb" },
    { value: 'Electronics', en: "Electronics", no: "Elektronikk" },
    { value: 'Book', en: "Book", no: "Bøker" },
    { value: 'Furniture', en: "Furniture", no: "Møbler" },
    { value: 'Clothing', en: "Clothing", no: "Klær" },
    { value: 'SellX', en: "SellX", no: "SellX" },
] as const satisfies readonly ListingOption[];
export type ProductCategory = (typeof PRODUCT_CATEGORY_OPTIONS)[number]['value'];

/** transactionType — Which values are legal depends on the category — see each form. */
export const TRANSACTION_TYPE_OPTIONS = [
    { value: 'for_sell', en: "For sale", no: "Til salgs" },
    { value: 'for_rent', en: "For rent", no: "Til leie" },
    { value: 'give_away', en: "Give away", no: "Gis bort" },
    { value: 'wants_to_buy', en: "Wants to buy", no: "Ønskes kjøpt" },
    { value: 'wants_to_rent', en: "Wanted to rent", no: "Ønskes leid" },
] as const satisfies readonly ListingOption[];
export type TransactionType = (typeof TRANSACTION_TYPE_OPTIONS)[number]['value'];

/** condition */
export const CONDITION_OPTIONS = [
    { value: 'new', en: "New", no: "Ny" },
    { value: 'used', en: "Used", no: "Brukt" },
] as const satisfies readonly ListingOption[];
export type Condition = (typeof CONDITION_OPTIONS)[number]['value'];

/** status — Read-only. A new listing starts as `draft` and becomes `active` on admin approval. */
export const PRODUCT_STATUS_OPTIONS = [
    { value: 'draft', en: "Draft", no: "Utkast" },
    { value: 'active', en: "Active", no: "Aktiv" },
    { value: 'sold', en: "Sold", no: "Solgt" },
    { value: 'expired', en: "Expired", no: "Utløpt" },
    { value: 'removed', en: "Removed", no: "Fjernet" },
    { value: 'rejected', en: "Rejected", no: "Avvist" },
] as const satisfies readonly ListingOption[];
export type ProductStatus = (typeof PRODUCT_STATUS_OPTIONS)[number]['value'];

/** promotion.plan — Read-only. */
export const PROMOTION_PLAN_OPTIONS = [
    { value: 'free', en: "Free", no: "Gratis" },
    { value: 'basic', en: "Basic", no: "Basis" },
    { value: 'standard', en: "Standard", no: "Standard" },
    { value: 'premium', en: "Premium", no: "Premium" },
    { value: 'featured', en: "Featured", no: "Fremhevet" },
    { value: 'urgent', en: "Urgent", no: "Haster" },
    { value: 'spotlight', en: "Spotlight", no: "Spotlight" },
] as const satisfies readonly ListingOption[];
export type PromotionPlan = (typeof PROMOTION_PLAN_OPTIONS)[number]['value'];

/** reason (POST /products/:id/report) */
export const REPORT_REASON_OPTIONS = [
    { value: 'spam_or_misleading', en: "Spam or misleading", no: "Spam eller villedende" },
    { value: 'scam_or_fraud', en: "Scam or fraud", no: "Svindel" },
    { value: 'inappropriate_content', en: "Inappropriate content", no: "Upassende innhold" },
    { value: 'wrong_category', en: "Wrong category", no: "Feil kategori" },
    { value: 'duplicate_listing', en: "Duplicate listing", no: "Duplikatannonse" },
    { value: 'fake_seller', en: "Fake seller", no: "Falsk selger" },
    { value: 'other', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type ReportReason = (typeof REPORT_REASON_OPTIONS)[number]['value'];

/**
 * type — The values the listing form accepts. `PropertyType` also carries `bygaard_flermannsbolig`
 * and `produksjon_industri`, which are on the filter page but on no form — creating with either is
 * a `400`, and filtering by either returns an empty list.
 */
export const PROPERTY_TYPE_OPTIONS = [
    { value: 'enebolig', en: "Detached house", no: "Enebolig" },
    { value: 'garasje_parkering', en: "Garage/Parking", no: "Garasje/Parkering" },
    { value: 'gaardsbruk_smaabruk', en: "Farm/Smallholding", no: "Gårdsbruk/Småbruk" },
    { value: 'leilighet', en: "Apartment", no: "Leilighet" },
    { value: 'rekkehus', en: "Townhouse", no: "Rekkehus" },
    { value: 'tomannsbolig', en: "Duplex", no: "Tomannsbolig" },
    { value: 'hytte', en: "Cabin", no: "Hytte" },
    { value: 'tomter', en: "Plots", no: "Tomter" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type PropertyType = (typeof PROPERTY_TYPE_OPTIONS)[number]['value'];

/** ownershipType */
export const OWNERSHIP_TYPE_OPTIONS = [
    { value: 'aksje', en: "Share", no: "Aksje" },
    { value: 'andel', en: "Co-op share", no: "Andel" },
    { value: 'eier_selveier', en: "Freehold", no: "Eier (Selveier)" },
    { value: 'obligasjon', en: "Bond", no: "Obligasjon" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type OwnershipType = (typeof OWNERSHIP_TYPE_OPTIONS)[number]['value'];

/** energyRating — A is the most efficient, G the least. */
export const ENERGY_RATING_OPTIONS = [
    { value: 'A', en: "A", no: "A" },
    { value: 'B', en: "B", no: "B" },
    { value: 'C', en: "C", no: "C" },
    { value: 'D', en: "D", no: "D" },
    { value: 'E', en: "E", no: "E" },
    { value: 'F', en: "F", no: "F" },
    { value: 'G', en: "G", no: "G" },
] as const satisfies readonly ListingOption[];
export type EnergyRating = (typeof ENERGY_RATING_OPTIONS)[number]['value'];

/**
 * heatingRating — Share of fossil fuel and electricity used for heating: dark green under 30%, red
 * over 82.5%.
 */
export const HEATING_RATING_OPTIONS = [
    { value: 'gul', en: "Yellow", no: "Gul" },
    { value: 'lysegronn', en: "Light green", no: "Lysegrønn" },
    { value: 'morkegronn', en: "Dark green", no: "Mørkegrønn" },
    { value: 'oransje', en: "Orange", no: "Oransje" },
    { value: 'rod', en: "Red", no: "Rød" },
] as const satisfies readonly ListingOption[];
export type HeatingRating = (typeof HEATING_RATING_OPTIONS)[number]['value'];

/** floorLevel — Send as a **string**, including the numeric floors. */
export const FLOOR_LEVEL_OPTIONS = [
    { value: 'kjeller', en: "Basement", no: "Kjeller" },
    { value: '1', en: "1st floor", no: "1. etasje" },
    { value: '2', en: "2nd floor", no: "2. etasje" },
    { value: '3', en: "3rd floor", no: "3. etasje" },
    { value: '4', en: "4th floor", no: "4. etasje" },
    { value: '5', en: "5th floor", no: "5. etasje" },
    { value: '6', en: "6th floor", no: "6. etasje" },
    { value: '7', en: "7th floor", no: "7. etasje" },
    { value: '8', en: "8th floor", no: "8. etasje" },
    { value: 'over_8', en: "Above 8th", no: "Over 8. etasje" },
] as const satisfies readonly ListingOption[];
export type FloorLevel = (typeof FLOOR_LEVEL_OPTIONS)[number]['value'];

/** furnishing */
export const FURNISHING_OPTIONS = [
    { value: 'mobelert', en: "Furnished", no: "Møblert" },
    { value: 'delvis_mobelert', en: "Partially furnished", no: "Delvis møblert" },
    { value: 'umobelert', en: "Unfurnished", no: "Umøblert" },
] as const satisfies readonly ListingOption[];
export type Furnishing = (typeof FURNISHING_OPTIONS)[number]['value'];

/**
 * preferredPropertyType — Wanted-to-rent only. Differs from `type`: it adds hybel and
 * rom_i_bofellesskap.
 */
export const PREFERRED_PROPERTY_TYPE_OPTIONS = [
    { value: 'hybel', en: "Studio apartment", no: "Hybel" },
    { value: 'garasje_parkering', en: "Garage/Parking", no: "Garasje/Parkering" },
    { value: 'tomannsbolig', en: "Duplex", no: "Tomannsbolig" },
    { value: 'enebolig', en: "Detached house", no: "Enebolig" },
    { value: 'rom_i_bofellesskap', en: "Room in shared housing", no: "Rom i bofellesskap" },
    { value: 'rekkehus', en: "Townhouse", no: "Rekkehus" },
    { value: 'leilighet', en: "Apartment", no: "Leilighet" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type PreferredPropertyType = (typeof PREFERRED_PROPERTY_TYPE_OPTIONS)[number]['value'];

/** preferredArea */
export const NORWEGIAN_AREA_OPTIONS = [
    { value: 'agder', en: "Agder", no: "Agder" },
    { value: 'akershus', en: "Akershus", no: "Akershus" },
    { value: 'bergen', en: "Bergen", no: "Bergen" },
    { value: 'buskerud', en: "Buskerud", no: "Buskerud" },
    { value: 'finnmark', en: "Finnmark", no: "Finnmark" },
    { value: 'innlandet', en: "Innlandet", no: "Innlandet" },
    { value: 'kristiansand', en: "Kristiansand", no: "Kristiansand" },
    { value: 'more_og_romsdal', en: "Møre og Romsdal", no: "Møre og Romsdal" },
    { value: 'nordland', en: "Nordland", no: "Nordland" },
    { value: 'oslo', en: "Oslo", no: "Oslo" },
    { value: 'rogaland', en: "Rogaland", no: "Rogaland" },
    { value: 'stavanger', en: "Stavanger", no: "Stavanger" },
    { value: 'svalbard', en: "Svalbard", no: "Svalbard" },
    { value: 'telemark', en: "Telemark", no: "Telemark" },
    { value: 'troms', en: "Troms", no: "Troms" },
    { value: 'trondelag', en: "Trøndelag", no: "Trøndelag" },
    { value: 'trondheim', en: "Trondheim", no: "Trondheim" },
    { value: 'vestfold', en: "Vestfold", no: "Vestfold" },
    { value: 'vestland', en: "Vestland", no: "Vestland" },
    { value: 'ostfold', en: "Østfold", no: "Østfold" },
] as const satisfies readonly ListingOption[];
export type NorwegianArea = (typeof NORWEGIAN_AREA_OPTIONS)[number]['value'];

/**
 * facilities — All 24 form options. The first ten are also filterable via `GET /filters/options`.
 */
export const PROPERTY_FACILITY_OPTIONS = [
    { value: 'balkong_terrasse', en: "Balcony/Terrace", no: "Balkong/terrasse" },
    { value: 'garasje_parkeringsplass', en: "Parking/Garage", no: "Garasje/Parkeringsplass" },
    { value: 'heis', en: "Elevator", no: "Heis" },
    { value: 'lademulighet', en: "EV charging", no: "Lademulighet" },
    { value: 'peis_ildsted', en: "Fireplace", no: "Peis/Ildsted" },
    { value: 'strandlinje', en: "Beachfront", no: "Strandlinje" },
    { value: 'turterreng', en: "Hiking trails", no: "Turterreng" },
    { value: 'utsikt', en: "Scenic view", no: "Utsikt" },
    { value: 'vaktmester', en: "Security service", no: "Vaktmester" },
    { value: 'ingen_gjenboere', en: "No overlooking neighbors", no: "Ingen gjenboere" },
    { value: 'klimaanlegg', en: "Air conditioning", no: "Klimaanlegg" },
    { value: 'takterrasse', en: "Rooftop terrace", no: "Takterrasse" },
    { value: 'felles_vaskeri', en: "Shared laundry", no: "Felles vaskeri" },
    { value: 'moderne', en: "Modern", no: "Moderne" },
    { value: 'fiskemuligheter', en: "Fishing spot", no: "Fiskemuligheter" },
    { value: 'alarm', en: "Alarm", no: "Alarm" },
    { value: 'barnevennlig', en: "Child-friendly", no: "Barnevennlig" },
    { value: 'bredband', en: "High-speed internet", no: "Bredbånd" },
    { value: 'kabel_tv', en: "Cable TV", no: "Kabel-TV" },
    { value: 'offentlig_vann_kloakk', en: "Public water/sewage", no: "Offentlig vann/kloakk" },
    { value: 'parkett', en: "Hardwood floors", no: "Parkett" },
    { value: 'rolig', en: "Quiet area", no: "Rolig område" },
    { value: 'sentralt', en: "Central location", no: "Sentralt" },
    { value: 'badeplass', en: "Swimming spot", no: "Badeplass" },
] as const satisfies readonly ListingOption[];
export type PropertyFacility = (typeof PROPERTY_FACILITY_OPTIONS)[number]['value'];

/** vehicleType — Selects which car form applies. */
export const VEHICLE_TYPE_OPTIONS = [
    { value: 'personbil', en: "Passenger car", no: "Personbil" },
    { value: 'campingvogn', en: "Caravan", no: "Campingvogn" },
    { value: 'bobil', en: "Motorhome", no: "Bobil" },
] as const satisfies readonly ListingOption[];
export type VehicleType = (typeof VEHICLE_TYPE_OPTIONS)[number]['value'];

/** vehicleLocation */
export const VEHICLE_LOCATION_OPTIONS = [
    { value: 'norge', en: "Norway", no: "Norge" },
    { value: 'utlandet', en: "Abroad", no: "Utlandet" },
] as const satisfies readonly ListingOption[];
export type VehicleLocation = (typeof VEHICLE_LOCATION_OPTIONS)[number]['value'];

/** taxClass */
export const TAX_CLASS_OPTIONS = [
    { value: 'kombinertbil', en: "Combined", no: "Kombinertbil" },
    { value: 'lett_lastebil', en: "Light truck", no: "Lett lastebil" },
    { value: 'minibuss', en: "Minibus", no: "Minibuss" },
    { value: 'personbil', en: "Passenger car", no: "Personbil" },
    { value: 'varebil', en: "Van", no: "Varebil" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type TaxClass = (typeof TAX_CLASS_OPTIONS)[number]['value'];

/** bodyType */
export const CAR_BODY_TYPE_OPTIONS = [
    { value: 'cabriolet', en: "Cabriolet", no: "Cabriolet" },
    { value: 'coupe', en: "Coupe", no: "Coupe" },
    { value: 'flerbruksbil', en: "Multi-purpose", no: "Flerbruksbil" },
    { value: 'kasse', en: "Van", no: "Kasse" },
    { value: 'kombi_3_dors', en: "Hatchback 3-door", no: "Kombi 3-dørs" },
    { value: 'kombi_5_dors', en: "Hatchback 5-door", no: "Kombi 5-dørs" },
    { value: 'pickup', en: "Pickup", no: "Pickup" },
    { value: 'suv_offroad', en: "SUV/Offroad", no: "SUV/Offroad" },
    { value: 'sedan', en: "Sedan", no: "Sedan" },
    { value: 'stasjonsvogn', en: "Estate", no: "Stasjonsvogn" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type CarBodyType = (typeof CAR_BODY_TYPE_OPTIONS)[number]['value'];

/** fuel */
export const CAR_FUEL_TYPE_OPTIONS = [
    { value: 'bensin', en: "Petrol", no: "Bensin" },
    { value: 'diesel', en: "Diesel", no: "Diesel" },
    { value: 'gass', en: "Gas", no: "Gass" },
    { value: 'elektrisitet', en: "Electric", no: "Elektrisitet" },
    { value: 'elektrisitet_bensin', en: "Electric + Petrol", no: "Elektrisitet + bensin" },
    { value: 'elektrisitet_diesel', en: "Electric + Diesel", no: "Elektrisitet + diesel" },
    { value: 'gass_bensin', en: "Gas + Petrol", no: "Gass + bensin" },
    { value: 'gass_diesel', en: "Gas + Diesel", no: "Gass + diesel" },
    { value: 'hydrogen', en: "Hydrogen", no: "Hydrogen" },
] as const satisfies readonly ListingOption[];
export type CarFuelType = (typeof CAR_FUEL_TYPE_OPTIONS)[number]['value'];

/** driveType */
export const DRIVE_TYPE_OPTIONS = [
    { value: 'forhjulsdrift', en: "Front-wheel drive", no: "Forhjulsdrift" },
    { value: 'bakhjulsdrift', en: "Rear-wheel drive", no: "Bakhjulsdrift" },
    { value: 'firehjulsdrift', en: "All-wheel drive", no: "Firehjulsdrift" },
] as const satisfies readonly ListingOption[];
export type DriveType = (typeof DRIVE_TYPE_OPTIONS)[number]['value'];

/** transmission */
export const TRANSMISSION_OPTIONS = [
    { value: 'manual', en: "Manual", no: "Manuell" },
    { value: 'automatic', en: "Automatic", no: "Automat" },
    { value: 'semi_automatic', en: "Semi-automatic", no: "Halvautomatisk" },
] as const satisfies readonly ListingOption[];
export type Transmission = (typeof TRANSMISSION_OPTIONS)[number]['value'];

/** warrantyType */
export const CAR_WARRANTY_TYPE_OPTIONS = [
    { value: 'nybilgaranti', en: "New car warranty", no: "Nybilgaranti" },
    { value: 'gammelbilgaranti_fra_forhandler', en: "Dealer warranty", no: "Gammelbilgaranti fra forhandler" },
] as const satisfies readonly ListingOption[];
export type CarWarrantyType = (typeof CAR_WARRANTY_TYPE_OPTIONS)[number]['value'];

/** warrantyType */
export const REMAINING_WARRANTY_TYPE_OPTIONS = [
    { value: 'resterende_ny_garanti', en: "Remaining new warranty", no: "Resterende ny garanti" },
    { value: 'resterende_brukt_garanti', en: "Remaining used warranty", no: "Resterende brukt garanti" },
] as const satisfies readonly ListingOption[];
export type RemainingWarrantyType = (typeof REMAINING_WARRANTY_TYPE_OPTIONS)[number]['value'];

/** conditionReportProvider */
export const CONDITION_REPORT_PROVIDER_OPTIONS = [
    { value: 'naf', en: "NAF", no: "NAF" },
    { value: 'viking', en: "Viking", no: "Viking" },
] as const satisfies readonly ListingOption[];
export type ConditionReportProvider = (typeof CONDITION_REPORT_PROVIDER_OPTIONS)[number]['value'];

/** motorhomeType */
export const MOTORHOME_TYPE_OPTIONS = [
    { value: 'alkove', en: "Alcove", no: "Alkove" },
    { value: 'bybobil', en: "City motorhome", no: "Bybobil" },
    { value: 'camper', en: "Camper", no: "Camper" },
    { value: 'delintegrert', en: "Semi-integrated", no: "Delintegrert" },
    { value: 'integrert', en: "Integrated", no: "Integrert" },
] as const satisfies readonly ListingOption[];
export type MotorhomeType = (typeof MOTORHOME_TYPE_OPTIONS)[number]['value'];

/** bedType */
export const BED_TYPE_OPTIONS = [
    { value: 'enkelseng', en: "Single bed", no: "Enkelseng" },
    { value: 'dobbeltseng', en: "Double bed", no: "Dobbeltseng" },
    { value: 'fransk_senglosning', en: "French bed", no: "Fransk sengløsning" },
    { value: 'tversgaende_seng', en: "Transverse bed", no: "Tversgående seng" },
] as const satisfies readonly ListingOption[];
export type BedType = (typeof BED_TYPE_OPTIONS)[number]['value'];

/** equipment (vehicleType: bobil) */
export const MOTORHOME_EQUIPMENT_OPTIONS = [
    { value: 'lettmetallfelger', en: "Alloy rims", no: "Lettmetallfelger" },
    { value: 'vinterhjul', en: "Winter wheels", no: "Vinterhjul" },
    { value: 'stotteben', en: "Support legs", no: "Støtteben" },
    { value: 'markise', en: "Awning", no: "Markise" },
    { value: 'hengerfeste', en: "Tow bar", no: "Hengerfeste" },
    { value: 'sykkelstativ', en: "Bike rack", no: "Sykkelstativ" },
    { value: 'takgrind_stige', en: "Roof rack/ladder", no: "Takgrind/Stige" },
    { value: 'abs_bremser', en: "ABS brakes", no: "ABS-bremser" },
    { value: 'gassalarm', en: "Gas alarm", no: "Gassalarm" },
    { value: 'bilalarm', en: "Vehicle alarm", no: "Bilalarm" },
    { value: 'airbag_forer', en: "Airbag driver", no: "Airbag fører" },
    { value: 'airbag_passasjer', en: "Airbag passenger", no: "Airbag passasjer" },
    { value: 'antiskrens', en: "Anti-skid", no: "Antiskrens" },
    { value: 'antispinn', en: "Traction control", no: "Antispinn" },
    { value: 'dieselpartikkelfilter', en: "Diesel particle filter", no: "Dieselpartikkelfilter" },
    { value: 'sentrallas', en: "Central locking", no: "Sentrallås" },
    { value: 'luftfjaering', en: "Air suspension", no: "Luftfjæring" },
    { value: 'klimaanlegg_bildel', en: "Air conditioning, cab", no: "Klimaanlegg bildel" },
    { value: 'klimaanlegg_bodel', en: "Air conditioning, living area", no: "Klimaanlegg bodel" },
    { value: 'elvarme', en: "Electric heating", no: "Elvarme" },
    { value: 'luftvarme', en: "Air heating", no: "Luftvarme" },
    { value: 'gulvvarme', en: "Underfloor heating", no: "Gulvvarme" },
    { value: 'vannbaren_varme', en: "Hydronic heating", no: "Vannbåren varme" },
    { value: 'tilleggsvarme', en: "Auxiliary heater (e.g. Webasto)", no: "Tilleggsvarme (f.eks. Webasto)" },
    { value: 'varmtvann', en: "Hot water", no: "Varmtvann" },
    { value: 'frostfri_vanntank', en: "Frost-free water tank", no: "Frostfri vanntank" },
    { value: 'frostfri_spillevanntank', en: "Frost-free waste water tank", no: "Frostfri spillevanntank" },
    { value: 'fast_toalett', en: "Fixed toilet", no: "Fast toalett" },
    { value: 'myggdor', en: "Mosquito door", no: "Myggdør" },
    { value: 'gassuttak', en: "Gas outlet", no: "Gassuttak" },
    { value: 'kjoleskap', en: "Refrigerator", no: "Kjøleskap" },
    { value: 'mikrobolgeovn', en: "Microwave", no: "Mikrobølgeovn" },
    { value: 'stekeovn', en: "Oven", no: "Stekeovn" },
    { value: 'elektriske_speil', en: "Electric mirrors", no: "Elektriske speil" },
    { value: 'elektriske_vinduer', en: "Electric windows", no: "Elektriske vinduer" },
    { value: 'skinninterior', en: "Leather interior", no: "Skinninteriør" },
    { value: 'lose_tepper', en: "Loose carpets", no: "Løse tepper" },
    { value: 'roykfri', en: "Smoke-free", no: "Røykfri" },
    { value: 'cruisekontroll', en: "Cruise control", no: "Cruisekontroll" },
    { value: 'ryggekamera', en: "Rear camera", no: "Ryggekamera" },
    { value: 'kjorecomputer', en: "Trip computer", no: "Kjørecomputer" },
    { value: 'navigasjonssystem', en: "Navigation system", no: "Navigasjonssystem" },
    { value: 'radio_cd', en: "Radio/CD", no: "Radio/CD" },
    { value: 'tv_antenne', en: "TV antenna", no: "TV-antenne" },
    { value: 'manuell_parabol', en: "Manual satellite dish", no: "Manuell parabol" },
    { value: 'automatisk_parabol', en: "Automatic satellite dish", no: "Automatisk parabol" },
    { value: 'tv', en: "TV", no: "TV" },
    { value: 'dvd', en: "DVD", no: "DVD" },
] as const satisfies readonly ListingOption[];
export type MotorhomeEquipment = (typeof MOTORHOME_EQUIPMENT_OPTIONS)[number]['value'];

/** equipment (vehicleType: campingvogn) */
export const CARAVAN_EQUIPMENT_OPTIONS = [
    { value: 'alu_felger', en: "Alloy rims", no: "Alu. felger" },
    { value: 'cruisekontroll', en: "Cruise control", no: "Cruisekontroll" },
    { value: 'dyrefri', en: "Pet-free", no: "Dyrefri" },
    { value: 'fast_toalett', en: "Fixed toilet", no: "Fast toalett" },
    { value: 'fortelt_sommer', en: "Awning, summer", no: "Fortelt, sommer" },
    { value: 'fortelt_vinter', en: "Awning, winter", no: "Fortelt, vinter" },
    { value: 'fryseboks', en: "Freezer", no: "Fryseboks" },
    { value: 'gassuttak', en: "Gas outlet", no: "Gassuttak" },
    { value: 'gulvvarme', en: "Underfloor heating", no: "Gulvvarme" },
    { value: 'koleskap', en: "Refrigerator", no: "Kjøleskap" },
    { value: 'mikrobolgeovn', en: "Microwave", no: "Mikrobølgeovn" },
    { value: 'radio_cd', en: "Radio/CD", no: "Radio/CD" },
    { value: 'radio_kassett', en: "Radio/cassette", no: "Radio/kassett" },
    { value: 'ryggekamera', en: "Rear camera", no: "Ryggekamera" },
    { value: 'roykefri', en: "Smoke-free", no: "Røykefri" },
    { value: 'sentralvarme', en: "Central heating", no: "Sentralvarme" },
    { value: 'sommerhjul', en: "Summer wheels", no: "Sommerhjul" },
    { value: 'midtarmlene', en: "Center armrest", no: "Midtarmlene" },
    { value: 'stekeovn', en: "Oven", no: "Stekeovn" },
    { value: 'sykkelstativ', en: "Bike rack", no: "Sykkelstativ" },
    { value: 'takgrind_stige', en: "Roof rack/ladder", no: "Takgrind/Stige" },
    { value: 'tv_antenne', en: "TV antenna", no: "TV-antenne" },
    { value: 'vannbaren_varme', en: "Hydronic heating", no: "Vannbåren varme" },
    { value: 'varmtvann', en: "Hot water", no: "Varmtvann" },
    { value: 'vinterhjul', en: "Winter wheels", no: "Vinterhjul" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type CaravanEquipment = (typeof CARAVAN_EQUIPMENT_OPTIONS)[number]['value'];

/** type */
export const BOAT_TYPE_OPTIONS = [
    { value: 'bowrider', en: "Bowrider", no: "Bowrider" },
    { value: 'cabincruiser', en: "Cabin cruiser", no: "Cabincruiser" },
    { value: 'daycruiser', en: "Daycruiser", no: "Daycruiser" },
    { value: 'gummibat_jolle', en: "Dinghy/Tender", no: "Gummibåt/Jolle" },
    { value: 'rib', en: "RIB", no: "RIB" },
    { value: 'seilbat_motorseiler', en: "Sailboat/Motorsailer", no: "Seilbåt/Motorseiler" },
    { value: 'skjaergaardsjeep', en: "Island hopper", no: "Skjærgårdsjeep/Landstedsbåt" },
    { value: 'pilothouse', en: "Pilothouse", no: "Pilothouse" },
    { value: 'speedbat', en: "Speedboat", no: "Speedbåt" },
    { value: 'trebat_snekke', en: "Wooden boat", no: "Trebåt/Snekke" },
    { value: 'yacht', en: "Yacht", no: "Yacht" },
    { value: 'vannscooter', en: "Jet ski", no: "Vannscooter" },
    { value: 'yrkesbat_sjark', en: "Commercial/Fishing", no: "Yrkesbåt/Sjark/Skøyte" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type BoatType = (typeof BOAT_TYPE_OPTIONS)[number]['value'];

/** fuel */
export const BOAT_FUEL_TYPE_OPTIONS = [
    { value: 'bensin', en: "Petrol", no: "Bensin" },
    { value: 'diesel', en: "Diesel", no: "Diesel" },
    { value: 'elektrisitet', en: "Electric", no: "Elektrisitet" },
    { value: 'hybrid', en: "Hybrid", no: "Hybrid" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type BoatFuelType = (typeof BOAT_FUEL_TYPE_OPTIONS)[number]['value'];

/** motorType */
export const MOTOR_TYPE_OPTIONS = [
    { value: 'innenbords', en: "Inboard", no: "Innenbords" },
    { value: 'utenbords', en: "Outboard", no: "Utenbords" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type MotorType = (typeof MOTOR_TYPE_OPTIONS)[number]['value'];

/** buildMaterial */
export const BUILD_MATERIAL_OPTIONS = [
    { value: 'plast', en: "Plastic", no: "Plast" },
    { value: 'glassfiber', en: "Fiberglass", no: "Glassfiber" },
    { value: 'tre', en: "Wood", no: "Tre" },
    { value: 'aluminium', en: "Aluminium", no: "Aluminium" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type BuildMaterial = (typeof BUILD_MATERIAL_OPTIONS)[number]['value'];

/** mcType — Selects which motorcycle form applies. */
export const MC_TYPE_OPTIONS = [
    { value: 'motorsykkel', en: "Motorcycle", no: "Motorsykkel" },
    { value: 'moped', en: "Moped", no: "Moped" },
    { value: 'atv', en: "ATV", no: "ATV" },
    { value: 'snoscooter', en: "Snowmobile", no: "Snøscooter" },
] as const satisfies readonly ListingOption[];
export type McType = (typeof MC_TYPE_OPTIONS)[number]['value'];

/** motorcycleType — Required when mcType is motorsykkel. */
export const MOTORCYCLE_TYPE_OPTIONS = [
    { value: 'chopper', en: "Chopper", no: "Chopper" },
    { value: 'cruiser', en: "Cruiser", no: "Cruiser" },
    { value: 'classic_nakne', en: "Classic/Naked", no: "Classic/Nakne" },
    { value: 'cross_enduro_trial', en: "Cross/Enduro/Trial", no: "Cross/Enduro/Trial" },
    { value: 'custom', en: "Custom", no: "Custom" },
    { value: 'lett_mc', en: "Light MC", no: "Lett MC" },
    { value: 'offroad_motard', en: "Offroad/Motard", no: "Offroad/Motard" },
    { value: 'scooter', en: "Scooter", no: "Scooter" },
    { value: 'sidevogn', en: "Sidecar", no: "Sidevogn" },
    { value: 'sport', en: "Sport", no: "Sport" },
    { value: 'touring', en: "Touring", no: "Touring" },
    { value: 'trike', en: "Trike", no: "Trike" },
    { value: 'veteran', en: "Veteran", no: "Veteran" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type MotorcycleType = (typeof MOTORCYCLE_TYPE_OPTIONS)[number]['value'];

/** mopedType — Required when mcType is moped. */
export const MOPED_TYPE_OPTIONS = [
    { value: 'moped', en: "Moped", no: "Moped" },
    { value: 'scooter', en: "Scooter", no: "Scooter" },
] as const satisfies readonly ListingOption[];
export type MopedType = (typeof MOPED_TYPE_OPTIONS)[number]['value'];

/** fuel */
export const MC_FUEL_TYPE_OPTIONS = [
    { value: 'bensin', en: "Petrol", no: "Bensin" },
    { value: 'diesel', en: "Diesel", no: "Diesel" },
    { value: 'elektrisitet', en: "Electric", no: "Elektrisitet" },
] as const satisfies readonly ListingOption[];
export type McFuelType = (typeof MC_FUEL_TYPE_OPTIONS)[number]['value'];

/** equipment */
export const MC_EQUIPMENT_OPTIONS = [
    { value: 'abs', en: "ABS", no: "ABS" },
    { value: 'traction_control', en: "Traction control", no: "Traction control" },
    { value: 'varmehandtak', en: "Heated grips", no: "Varmehåndtak" },
    { value: 'varmesete', en: "Heated seat", no: "Varmesete" },
    { value: 'uttak_12v', en: "12V outlet", no: "12V uttak" },
    { value: 'hoyttalere', en: "Speakers", no: "Høyttalere" },
    { value: 'sidevesker', en: "Side bags", no: "Sidevesker" },
    { value: 'radio_cd_mp3', en: "Radio/CD/MP3", no: "Radio/CD/MP3" },
    { value: 'handbeskyttere', en: "Hand guards", no: "Håndbeskyttere" },
    { value: 'tankpad', en: "Tank pad", no: "Tankpad" },
    { value: 'tanktrekk', en: "Tank cover", no: "Tanktrekk" },
    { value: 'tankveske', en: "Tank bag", no: "Tankveske" },
    { value: 'toppveske', en: "Top case", no: "Toppveske" },
    { value: 'gaffelveske', en: "Fork bag", no: "Gaffelveske" },
    { value: 'vindskjerm', en: "Windshield", no: "Vindskjerm" },
    { value: 'alarm', en: "Alarm", no: "Alarm" },
    { value: 'bagasjebrett', en: "Luggage rack", no: "Bagasjebrett" },
    { value: 'solodeksel', en: "Solo seat cover", no: "Solodeksel" },
    { value: 'velteklosser', en: "Crash bars", no: "Velteklosser" },
    { value: 'koppholder', en: "Cup holder", no: "Koppholder" },
    { value: 'ekstra_kaper', en: "Extra fairings", no: "Ekstra kåper" },
    { value: 'intercom', en: "Intercom", no: "Intercom" },
    { value: 'overtrekk', en: "Cover", no: "Overtrekk" },
    { value: 'navigasjonssystem', en: "Navigation system", no: "Navigasjonssystem" },
    { value: 'effektanlegg', en: "Performance exhaust", no: "Effektanlegg" },
    { value: 'xenon_lys', en: "Xenon light", no: "Xenon-lys" },
    { value: 'cruise_control', en: "Cruise control", no: "Cruise control" },
    { value: 'kjorecomputer', en: "Trip computer", no: "Kjørecomputer" },
    { value: 'slepekrok', en: "Tow hook", no: "Slepekrok" },
    { value: 'revers', en: "Reverse gear", no: "Revers" },
    { value: 'aut_demperjustering', en: "Automatic damper adjustment", no: "Aut. demperjustering" },
    { value: 'midtstotte', en: "Center stand", no: "Midtstøtte" },
    { value: 'led_lys', en: "LED light", no: "LED-lys" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type McEquipment = (typeof MC_EQUIPMENT_OPTIONS)[number]['value'];

/** bikeType */
export const BIKE_TYPE_OPTIONS = [
    { value: 'bmx', en: "BMX", no: "BMX" },
    { value: 'cyclocross_gravel', en: "Cyclocross/Gravel", no: "Cyclocross/gravel" },
    { value: 'elektriske', en: "Electric", no: "Elektriske" },
    { value: 'fulldamper', en: "Full suspension", no: "Fulldamper" },
    { value: 'hybrid', en: "Hybrid", no: "Hybrid" },
    { value: 'landevei', en: "Road", no: "Landevei" },
    { value: 'terreng', en: "Mountain", no: "Terreng" },
    { value: 'barnesykkel_2_12', en: "Children's bike 2-12 yr", no: "Barnesykkel 2-12 år" },
    { value: 'bysykkel_sammenleggbare', en: "City/Folding", no: "Bysykkel/sammenleggbare" },
    { value: 'sparkesykkel', en: "Kick scooter", no: "Sparkesykkel" },
    { value: 'trehjulssykkel_lopesykkel', en: "Tricycle/Balance bike", no: "Trehjulssykkel/løpesykkel" },
    { value: 'andre', en: "Other", no: "Andre" },
] as const satisfies readonly ListingOption[];
export type BikeType = (typeof BIKE_TYPE_OPTIONS)[number]['value'];

/** bookCategory */
export const BOOK_CATEGORY_OPTIONS = [
    { value: 'videregaende', en: "High school books", no: "Videregående bøker" },
    { value: 'universitet', en: "University books", no: "Universitetsbøker" },
    { value: 'barneboker', en: "Children's books", no: "Barnebøker" },
    { value: 'romaner', en: "Novels", no: "Romaner" },
] as const satisfies readonly ListingOption[];
export type BookCategory = (typeof BOOK_CATEGORY_OPTIONS)[number]['value'];

/** employmentType */
export const EMPLOYMENT_TYPE_OPTIONS = [
    { value: 'deltid', en: "Part-time", no: "Deltid" },
    { value: 'heltid', en: "Full-time", no: "Heltid" },
    { value: 'lederstilling', en: "Management position", no: "Lederstilling" },
] as const satisfies readonly ListingOption[];
export type EmploymentType = (typeof EMPLOYMENT_TYPE_OPTIONS)[number]['value'];

/**
 * contractType — The values the listing form accepts. `ContractType` also carries `bemanningsbyra`,
 * which is on the filter page but on no form — creating with it is a `400`, and filtering by it
 * returns an empty list.
 */
export const CONTRACT_TYPE_OPTIONS = [
    { value: 'engasjement', en: "Engagement", no: "Engasjement" },
    { value: 'fast', en: "Permanent", no: "Fast" },
    { value: 'laerling', en: "Apprentice", no: "Lærling" },
    { value: 'prosjekt', en: "Project", no: "Prosjekt" },
    { value: 'selvstendig_naeringsdrivende', en: "Self-employed", no: "Selvstendig næringsdrivende" },
    { value: 'sommer_sesong', en: "Summer/Seasonal", no: "Sommer/Sesong" },
    { value: 'trainee', en: "Trainee", no: "Trainee" },
    { value: 'vikariat', en: "Temporary", no: "Vikariat" },
] as const satisfies readonly ListingOption[];
export type ContractType = (typeof CONTRACT_TYPE_OPTIONS)[number]['value'];

/** sector */
export const SECTOR_OPTIONS = [
    { value: 'franchise_selvstendig', en: "Franchise/Self-employed", no: "Franchise/Selvstendig næringsdrivende" },
    { value: 'offentlig', en: "Public", no: "Offentlig" },
    { value: 'organisasjoner', en: "Organizations", no: "Organisasjoner" },
    { value: 'privat', en: "Private", no: "Privat" },
    { value: 'samvirke', en: "Cooperative", no: "Samvirke" },
] as const satisfies readonly ListingOption[];
export type Sector = (typeof SECTOR_OPTIONS)[number]['value'];

/** workLanguage */
export const WORK_LANGUAGE_OPTIONS = [
    { value: 'norsk', en: "Norwegian", no: "Norsk" },
    { value: 'engelsk', en: "English", no: "Engelsk" },
] as const satisfies readonly ListingOption[];
export type WorkLanguage = (typeof WORK_LANGUAGE_OPTIONS)[number]['value'];

/** remoteWorkType */
export const REMOTE_WORK_TYPE_OPTIONS = [
    { value: 'delvis_hjemmearbeid', en: "Partly remote", no: "Delvis hjemmearbeid" },
    { value: 'kun_hjemmearbeid', en: "Fully remote", no: "Kun hjemmearbeid" },
] as const satisfies readonly ListingOption[];
export type RemoteWorkType = (typeof REMOTE_WORK_TYPE_OPTIONS)[number]['value'];

/** equipment (vehicleType: personbil), grouped as the form renders it. */
export const CAR_EQUIPMENT_GROUPS = {
    komfort: [
        { value: 'air_condition', en: "Air condition", no: "Air Condition" },
        { value: 'klimaanlegg', en: "Air conditioning", no: "Klimaanlegg" },
        { value: 'bagasjeromstrekk', en: "Luggage compartment cover", no: "Bagasjeromstrekk" },
        { value: 'cruisekontroll', en: "Cruise control", no: "Cruisekontroll" },
        { value: 'adaptiv_cruisekontroll', en: "Adaptive cruise control", no: "Adaptiv cruisekontroll" },
        { value: 'elektrisk_sete_med_minne', en: "Electric seat with memory", no: "Elektrisk sete med minne" },
        { value: 'elektrisk_sete_uten_minne', en: "Electric seat without memory", no: "Elektrisk sete uten minne" },
        { value: 'kupevarmer', en: "Interior heater", no: "Kupévarmer" },
        { value: 'luftfjaering', en: "Air suspension", no: "Luftfjæring" },
        { value: 'midtarmlener', en: "Center armrests", no: "Midtarmlener" },
        { value: 'motorvarmer', en: "Engine heater", no: "Motorvarmer" },
        { value: 'nivaregulering', en: "Level control", no: "Nivåregulering" },
        { value: 'keyless_start', en: "Keyless start", no: "Keyless start" },
        { value: 'setevarme', en: "Heated seats", no: "Setevarme" },
        { value: 'sentrallas', en: "Central locking", no: "Sentrallås" },
        { value: 'delskinnseter', en: "Partial leather seat", no: "Delskinnseter" },
        { value: 'helskinnseter', en: "Full leather seat", no: "Helskinnseter" },
        { value: 'soltak_glasstak', en: "Sunroof/glass roof", no: "Soltak/glasstak" },
        { value: 'sportsseter', en: "Sport seats", no: "Sportsseter" },
        { value: 'morke_bakruter', en: "Dark rear windows", no: "Mørke bakruter" },
        { value: 'parkeringssensor_bak', en: "Rear parking sensor", no: "Parkeringssensor bak" },
        { value: 'parkeringssensor_foran', en: "Front parking sensor", no: "Parkeringssensor foran" },
        { value: 'ryggekamera', en: "Rear camera", no: "Ryggekamera" },
    ],
    sikkerhet: [
        { value: 'abs_bremser', en: "ABS brakes", no: "ABS-bremser" },
        { value: 'airbag_foran', en: "Airbag front", no: "Airbag foran" },
        { value: 'alarm', en: "Alarm", no: "Alarm" },
        { value: 'gjenfinningssystem', en: "Recovery system", no: "Gjenfinningssystem" },
        { value: 'isofix', en: "Isofix", no: "Isofix" },
        { value: 'sidekollisjonsputer', en: "Side airbag", no: "Sidekollisjonsputer" },
        { value: 'startsperre', en: "Immobilizer", no: "Startsperre" },
        { value: 'antiskrens', en: "Anti-skid", no: "Antiskrens" },
        { value: 'dieselpartikkelfilter', en: "Diesel particle filter", no: "Dieselpartikkelfilter" },
        { value: 'diff_sperre', en: "Diff. lock", no: "Diff. sperre" },
        { value: 'servostyring', en: "Power steering", no: "Servostyring" },
        { value: 'hengerfeste_avtagbar', en: "Tow bar, removable/swivel", no: "Hengerfeste, avtagbar/svingbar" },
        { value: 'hengerfeste_fast_krok', en: "Tow bar, fixed hook", no: "Hengerfeste, fast krok" },
        { value: 'laserlys', en: "Laser light", no: "Laserlys" },
        { value: 'led_lys', en: "LED light", no: "LED-lys" },
        { value: 'xenon_lys', en: "Xenon light", no: "Xenon-lys" },
        { value: 'fjernlysassistent', en: "High beam assistant", no: "Fjernlysassistent" },
        { value: 'lyssensor', en: "Light sensor", no: "Lyssensor" },
        { value: 'regnsensor', en: "Rain sensor", no: "Regnsensor" },
    ],
    motor_og_ytelse: [
        { value: 'kjorecomputer', en: "Trip computer", no: "Kjørecomputer" },
    ],
    teknologi: [
        { value: 'bluetooth', en: "Bluetooth", no: "Bluetooth" },
        { value: 'cd_spiller', en: "CD player", no: "CD-spiller" },
        { value: 'handfrisystem', en: "Hands-free system", no: "Håndfrisystem" },
        { value: 'head_up_display', en: "Head up display", no: "Head up display" },
        { value: 'navigasjonssystem', en: "Navigation system", no: "Navigasjonssystem" },
        { value: 'original_telefon', en: "Original phone", no: "Original telefon" },
        { value: 'radio_dab_plus', en: "Radio DAB+", no: "Radio DAB+" },
        { value: 'radio_fm', en: "Radio FM", no: "Radio FM" },
        { value: 'tv_skjerm_bak', en: "TV screen in the rear seat", no: "TV-skjerm i baksetet" },
    ],
    eksterior: [
        { value: 'takgrind_skistativ', en: "Cargo carriers/ski rack", no: "Takgrind/skistativ" },
        { value: 'lettmetallfelger_sommer', en: "Alloy rims, summer", no: "Lettmetallfelger, sommer" },
        { value: 'lettmetallfelger_vinter', en: "Alloy rims, winter", no: "Lettmetallfelger, vinter" },
        { value: 'metallic_lakk', en: "Metallic paint", no: "Metallic lakk" },
        { value: 'takrails', en: "Roof rails", no: "Takrails" },
        { value: 'sommerhjul', en: "Summer wheels", no: "Sommerhjul" },
        { value: 'vinterhjul', en: "Winter wheels", no: "Vinterhjul" },
        { value: 'elektriske_speil', en: "Electric mirrors", no: "Elektriske speil" },
        { value: 'elektriske_vinduer', en: "Electric windows", no: "Elektriske vinduer" },
    ],
} as const;

/** Every car equipment value, flattened. */
export const CAR_EQUIPMENT_OPTIONS = [
    { value: 'air_condition', en: "Air condition", no: "Air Condition" },
    { value: 'klimaanlegg', en: "Air conditioning", no: "Klimaanlegg" },
    { value: 'bagasjeromstrekk', en: "Luggage compartment cover", no: "Bagasjeromstrekk" },
    { value: 'cruisekontroll', en: "Cruise control", no: "Cruisekontroll" },
    { value: 'adaptiv_cruisekontroll', en: "Adaptive cruise control", no: "Adaptiv cruisekontroll" },
    { value: 'elektrisk_sete_med_minne', en: "Electric seat with memory", no: "Elektrisk sete med minne" },
    { value: 'elektrisk_sete_uten_minne', en: "Electric seat without memory", no: "Elektrisk sete uten minne" },
    { value: 'kupevarmer', en: "Interior heater", no: "Kupévarmer" },
    { value: 'luftfjaering', en: "Air suspension", no: "Luftfjæring" },
    { value: 'midtarmlener', en: "Center armrests", no: "Midtarmlener" },
    { value: 'motorvarmer', en: "Engine heater", no: "Motorvarmer" },
    { value: 'nivaregulering', en: "Level control", no: "Nivåregulering" },
    { value: 'keyless_start', en: "Keyless start", no: "Keyless start" },
    { value: 'setevarme', en: "Heated seats", no: "Setevarme" },
    { value: 'sentrallas', en: "Central locking", no: "Sentrallås" },
    { value: 'delskinnseter', en: "Partial leather seat", no: "Delskinnseter" },
    { value: 'helskinnseter', en: "Full leather seat", no: "Helskinnseter" },
    { value: 'soltak_glasstak', en: "Sunroof/glass roof", no: "Soltak/glasstak" },
    { value: 'sportsseter', en: "Sport seats", no: "Sportsseter" },
    { value: 'morke_bakruter', en: "Dark rear windows", no: "Mørke bakruter" },
    { value: 'parkeringssensor_bak', en: "Rear parking sensor", no: "Parkeringssensor bak" },
    { value: 'parkeringssensor_foran', en: "Front parking sensor", no: "Parkeringssensor foran" },
    { value: 'ryggekamera', en: "Rear camera", no: "Ryggekamera" },
    { value: 'abs_bremser', en: "ABS brakes", no: "ABS-bremser" },
    { value: 'airbag_foran', en: "Airbag front", no: "Airbag foran" },
    { value: 'alarm', en: "Alarm", no: "Alarm" },
    { value: 'gjenfinningssystem', en: "Recovery system", no: "Gjenfinningssystem" },
    { value: 'isofix', en: "Isofix", no: "Isofix" },
    { value: 'sidekollisjonsputer', en: "Side airbag", no: "Sidekollisjonsputer" },
    { value: 'startsperre', en: "Immobilizer", no: "Startsperre" },
    { value: 'antiskrens', en: "Anti-skid", no: "Antiskrens" },
    { value: 'dieselpartikkelfilter', en: "Diesel particle filter", no: "Dieselpartikkelfilter" },
    { value: 'diff_sperre', en: "Diff. lock", no: "Diff. sperre" },
    { value: 'servostyring', en: "Power steering", no: "Servostyring" },
    { value: 'hengerfeste_avtagbar', en: "Tow bar, removable/swivel", no: "Hengerfeste, avtagbar/svingbar" },
    { value: 'hengerfeste_fast_krok', en: "Tow bar, fixed hook", no: "Hengerfeste, fast krok" },
    { value: 'laserlys', en: "Laser light", no: "Laserlys" },
    { value: 'led_lys', en: "LED light", no: "LED-lys" },
    { value: 'xenon_lys', en: "Xenon light", no: "Xenon-lys" },
    { value: 'fjernlysassistent', en: "High beam assistant", no: "Fjernlysassistent" },
    { value: 'lyssensor', en: "Light sensor", no: "Lyssensor" },
    { value: 'regnsensor', en: "Rain sensor", no: "Regnsensor" },
    { value: 'kjorecomputer', en: "Trip computer", no: "Kjørecomputer" },
    { value: 'bluetooth', en: "Bluetooth", no: "Bluetooth" },
    { value: 'cd_spiller', en: "CD player", no: "CD-spiller" },
    { value: 'handfrisystem', en: "Hands-free system", no: "Håndfrisystem" },
    { value: 'head_up_display', en: "Head up display", no: "Head up display" },
    { value: 'navigasjonssystem', en: "Navigation system", no: "Navigasjonssystem" },
    { value: 'original_telefon', en: "Original phone", no: "Original telefon" },
    { value: 'radio_dab_plus', en: "Radio DAB+", no: "Radio DAB+" },
    { value: 'radio_fm', en: "Radio FM", no: "Radio FM" },
    { value: 'tv_skjerm_bak', en: "TV screen in the rear seat", no: "TV-skjerm i baksetet" },
    { value: 'takgrind_skistativ', en: "Cargo carriers/ski rack", no: "Takgrind/skistativ" },
    { value: 'lettmetallfelger_sommer', en: "Alloy rims, summer", no: "Lettmetallfelger, sommer" },
    { value: 'lettmetallfelger_vinter', en: "Alloy rims, winter", no: "Lettmetallfelger, vinter" },
    { value: 'metallic_lakk', en: "Metallic paint", no: "Metallic lakk" },
    { value: 'takrails', en: "Roof rails", no: "Takrails" },
    { value: 'sommerhjul', en: "Summer wheels", no: "Sommerhjul" },
    { value: 'vinterhjul', en: "Winter wheels", no: "Vinterhjul" },
    { value: 'elektriske_speil', en: "Electric mirrors", no: "Elektriske speil" },
    { value: 'elektriske_vinduer', en: "Electric windows", no: "Elektriske vinduer" },
] as const satisfies readonly ListingOption[];
export type CarEquipment = (typeof CAR_EQUIPMENT_OPTIONS)[number]['value'];

/* ---------- Categories ---------- */

/**
 * `category` on a listing -> the slug the filter endpoints take,
 * e.g. `GET /filters/options?category=car`.
 */
export const CATEGORY_FILTER_SLUGS = {
    'Car': 'car',
    'Property': 'property',
    'Boat': 'boat',
    'Motorcycle': 'motorcycle',
    'Bike': 'bike',
    'Job': 'job',
    'Electronics': 'electronics',
    'Book': 'book',
    'Furniture': 'furniture',
    'Clothing': 'clothing',
    'SellX': 'sellx',
} as const satisfies Record<ProductCategory, string>;

/* ---------- Brands and models ---------- */

/**
 * Brand names are proper nouns and read the same in both languages, so the lists ship as
 * plain strings. Wrap one with `brandOptions()` where a select wants `ListingOption`.
 * The server validates against these exact strings, so do not re-case or re-sort them.
 */
export const brandOptions = (brands: readonly string[]): ListingOption[] =>
    brands.map((value) => ({ value, en: value, no: value }));

/**
 * brand (category: Car, vehicleType: personbil) — 117 entries. Required, and `carModel` must be a
 * model of that same brand. Every list ends with `Andre` ("Other").
 */
export const CAR_BRAND_OPTIONS = [
    'Abarth', 'ACE', 'AC', 'Addax', 'Alfa Romeo', 'Alpina', 'AMC', 'Ariel', 'Aston Martin', 'Audi',
    'Austin', 'BMW', 'Bentley', 'Buddy', 'Buick', 'Bugatti', 'BYD', 'Cadillac', 'Chevrolet',
    'Chrysler', 'Citroën', 'Cupra', 'DAF', 'DS', 'Dacia', 'Daewoo', 'Daihatsu', 'Datsun',
    'Detomaso', 'Delorean', 'Dodge', 'Ferrari', 'Fiat', 'Fisker', 'Ford', 'GMC', 'Goupil', 'Hiphi',
    'Honda', 'Hongqi', 'Hummer', 'Hyundai', 'Infiniti', 'Isuzu', 'Iveco', 'JAC', 'Jaguar', 'Jeep',
    'Jensen', 'Kewet', 'Kia', 'Koenigsegg', 'Lada', 'Lamborghini', 'Lancia', 'Lucid', 'Land Rover',
    'Lexus', 'Lincoln', 'Lotus', 'MAN', 'Mia Electric', 'MG', 'Mini', 'Maserati', 'Matra', 'Maxus',
    'Maybach', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mercury', 'Mitsubishi', 'Morgan', 'Morris',
    'Nio', 'Nissan', 'Nosmoke', 'Oldsmobile', 'Opel', 'Packard', 'Panther', 'Peugeot', 'Piaggio',
    'Plymouth', 'Polestar', 'Pontiac', 'Porsche', 'Radical', 'RAM', 'Renault', 'Reva',
    'Rolls-Royce', 'Rover', 'Saab', 'Santana', 'Scion', 'SEAT', 'Seres', 'Skoda', 'Smart',
    'SsangYong', 'Subaru', 'Suzuki', 'TVR', 'Tazzari', 'Tesla', 'Think', 'Toyota', 'Triumph',
    'Volkswagen', 'Volvo', 'Voyah', 'Wiesmann', 'XPeng', 'ZD', 'Andre',
] as const;
export type CarBrand = (typeof CAR_BRAND_OPTIONS)[number];

/** carModel — 1457 models across 117 brands. A model is only valid under its own brand. */
export const CAR_MODELS_BY_BRAND = {
    'Abarth': ['124 Spider', '500', '595', '695'],
    'ACE': ['Andre'],
    'AC': ['Cobra', 'Matador'],
    'Addax': ['MT', 'MTN'],
    'Alfa Romeo': [
        '145', '147', '155', '156', '159', '164', '166', '33', '4C', '75', '90', 'Alfasud',
        'Alfetta', 'Brera', 'GT', 'GTV', 'Giulia Quadrifoglio', 'Giulietta',
        'Giulietta (gml. type)', 'MiTo', 'Spider', 'Sprint', 'Stelvio', 'Stelvio Quadrifoglio',
        'Tonale', 'Andre',
    ],
    'Alpina': [
        'A110', 'B10', 'B12', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8', 'D10', 'D3', 'D4', 'D5',
        'Roadster S', 'XD3',
    ],
    'AMC': ['Andre'],
    'Ariel': ['Atom'],
    'Aston Martin': [
        'Cygnet', 'DB7', 'DB9', 'DB11', 'DB11 Volante', 'DBS Superleggera', 'DBX', 'Rapide',
        'V12 Vantage', 'V8 Vantage', 'Vanquish', 'Virage', 'Andre',
    ],
    'Audi': [
        'A1', 'A2', 'A3', 'A4', 'A4 allroad', 'A5', 'A6', 'A6 allroad', 'A7', 'A8', 'Q2', 'Q3',
        'Q4 e-tron', 'Q5', 'Q7', 'Q8', 'Q8 e-tron', 'R8', 'RS2', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7',
        'RSQ3', 'RSQ8', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'SQ5', 'SQ7', 'SQ8', 'TT',
        'V8', 'e-tron', 'e-tron GT RS', 'e-tron GT', 'e-tron Sportback', '50', '60', '80', '90',
        '100', '200', 'Andre',
    ],
    'Austin': ['Healey 100 6', 'Healey 3000', 'Princess', 'Andre'],
    'BMW': [
        '1-serie', '1M', '2-serie', '3-serie', '4-serie', '5-serie', '6-serie', '7-serie',
        '8-serie', '3-serie GT', '5-serie GT', 'M2', 'M3', 'M4', 'M5', 'M6', 'X1', 'X2', 'X3',
        'X3 M', 'X4', 'X4 M', 'X5', 'X5 M', 'X6', 'X6 M', 'X7', 'XM', 'M8', 'Z1', 'Z3', 'Z4', 'Z8',
        'i3', 'i4', 'i4 M50', 'i5', 'i5 M60', 'i7', 'i8', 'iX1', 'iX3', 'iX40', 'iX M60',
        'iX xDrive 40', 'iX xDrive 40', 'iX xDrive M60', '1500', '1600', '1602', '1800', '2000',
        '2002', '2500', '2800', 'Andre',
    ],
    'Bentley': [
        'Arnage', 'Bentayga', 'Continental GT', 'Continental GTC', 'Flying Spur', 'Mulsanne',
        'Andre',
    ],
    'Buddy': [
        'Basic', 'Citi-Jet 6', 'Classic Basis', 'Classic Cab', 'Classic Pluss', 'Pluss', 'Premium',
    ],
    'Buick': ['Centurion', 'Century', 'Le Sabre', 'Park Avenue', 'Regal', 'Skylark'],
    'Bugatti': ['Chiron', 'Andre'],
    'BYD': ['Atto3', 'Han', 'T3', 'Tang', 'Andre'],
    'Cadillac': [
        'ATS', 'BLS', 'CTS', 'Deville', 'Eldorado', 'Elr', 'Escalade', 'Fleetwood', 'SRX',
        'Seville', 'XLR', 'Andre',
    ],
    'Chevrolet': [
        'Alero', 'Astro', 'Avalanche', 'Aveo', 'Beauville', 'Bel Air', 'Beretta', 'Big Dooley',
        'Blazer', 'Bolt', 'C-10', 'Camaro', 'Caprice', 'Captiva', 'Cargovan', 'Chevelle',
        'Cheyenne', 'Colorado', 'Corsica', 'Corvair', 'Corvette', 'Crew Cab', 'Cruze', 'El Camino',
        'Epica', 'Express', 'Extended Cab', 'Impala', 'Kalos', 'Korea', 'Lacetti', 'Lumina',
        'Malibu', 'Master', 'Matiz', 'Monte Carlo', 'Nubira', 'Orlando', 'Regular Cab', 'S-10',
        'Silverado', 'Spark', 'Sport Van', 'Starcraft', 'Suburban', 'Tahoe', 'Trailblazer',
        'Trans Sport', 'Trax', 'Van', 'Volt',
    ],
    'Chrysler': [
        '300 M', '300C', 'Crossfire', 'Grand Voyager', 'Le Baron', 'Neon', 'New Yorker',
        'PT Cruiser', 'Pacifica', 'Plymouth Premier', 'Plymouth Volare', 'Prowler', 'Sebring',
        'Stratus', 'Vision', 'Voyager', 'Andre',
    ],
    'Citroën': [
        '2CV', 'AX', 'BX', 'Berlingo', 'Berlingo Electrique', 'C-Crosser', 'C-Zero', 'C1', 'C2',
        'C3', 'C3 Aircross', 'C3 Picasso', 'C4', 'C4 Aircross', 'C4 Cactus', 'C4 Picasso', 'C5',
        'C5 Aircross', 'C5 X', 'C6', 'C8', 'CX', 'DS3', 'DS4', 'DS5', 'E-C4', 'E-C4 X', 'E-Mehari',
        'Evasion', 'GSA', 'Grand C4 Picasso', 'Grand C4 Spacetourer', 'Jumper', 'Jumpy', 'Nemo',
        'SAXO Electrique', 'Saxo', 'Space Tourer', 'Visa', 'XM', 'Xantia', 'Xsara', 'Xsara Picasso',
        'ZX',
    ],
    'Cupra': ['Formentor', 'Formentor e-HYBRID', 'Leon e-Racer', 'Born'],
    'DAF': ['Andre'],
    'DS': ['DS 3', '3 Crossback', 'DS 4', 'DS 5', 'DS 7 Crossback', 'DS 9'],
    'Dacia': ['Duster', 'Logan', 'Dokker', 'Andre'],
    'Daewoo': [
        'Espero', 'Kalos', 'Koranda', 'Lacetti', 'Lanos', 'Leganza', 'Matiz', 'Musso', 'Nexia',
        'Nubira', 'Tacuma', 'Andre',
    ],
    'Daihatsu': [
        'Applause', 'Charade', 'Copen', 'Cuore', 'Gran Move', 'Rocky', 'Sirion', 'Terios', 'YRV',
        'Andre',
    ],
    'Datsun': ['Datsun', 'Andre'],
    'Detomaso': ['Pantera', 'Andre'],
    'Delorean': ['DMC-12', 'Andre'],
    'Dodge': [
        'Avenger', 'Caliber', 'Challenger', 'Charger', 'Dakota', 'Durango', 'Grand Caravan',
        'Journey', 'Le Baron', 'Magnum', 'Nitro', 'RAM', 'RAM STR-10', 'Viper', 'Andre',
    ],
    'Ferrari': [
        '296', '308', '328', '348', '355', '360', '365', '412', '430', '456', '458 Italia',
        '458 Spider', '488 GTB', '488 Spider', '488 Pista', '512', '550 Maranello', '575 Maranello',
        '599', '612', '812 GTS', '812 Superfast', 'California', 'Dino', 'F8 Spider', 'F8 Tributo',
        'F 40', 'F12 Berlinetta', 'FF', 'GTC4Lusso', 'Mondial', 'Portofino', 'Roma', 'SF90 Spider',
        'SF90 Stradale', 'Testarossa', 'Andre',
    ],
    'Fiat': [
        '124 Spider', '500', '500L', '500X', 'Barchetta', 'Bertone', 'Brava', 'Bravo', 'Coupe',
        'Croma', 'Doblo', 'Ducato', 'Freemont', 'Fullback', 'Grande Punto', 'Marea', 'Multipla',
        'Panda', 'Punto', 'Punto Evo', 'Regata', 'Ritmo', 'Scudo', 'Sedici', 'Stilo', 'Starda',
        'Talento', 'Tipo', 'Ulysse', 'Uno', 'X 1/9', 'Andre',
    ],
    'Fisker': ['Karma', 'Karma S', 'Ocean', 'Andre'],
    'Ford': [
        'Aerostar', 'B-MAX', 'Bronco', 'C-Max', 'Cougar', 'Courier', 'Custom Line', 'Econoline',
        'Ecosport', 'Edge', 'Escort', 'Excursion', 'Expedition', 'Explorer', 'Extended Cab',
        'F-serie', 'Fiesta', 'Focus', 'Focus CC', 'Fusion', 'Galaxy', 'Granada', 'Grand C-MAX',
        'Grand Tourneo Connect', 'Ka', 'Ka+', 'Kuga', 'Maverick', 'Mondeo', 'Mustang',
        'Mustang Mach-E', 'Orion', 'Probe', 'Puma', 'Ranger', 'S-MAX', 'SVT Lightning', 'Scorpio',
        'Sirra', 'Sportka', 'StreetKa', 'Taunus', 'Taurus', 'Thunderbird', 'Tourneo Connect',
        'Tourneo Courier', 'Tourneo Custom', 'Transit', 'Transit Connect', 'Transit Courier',
        'Transit Custom', 'Van', 'Windstar', 'Andre',
    ],
    'GMC': [
        'Crew Cab', 'Envoy', 'Extended Cab', 'Sierra', 'Silverado', 'Syclone', 'Yukon', 'Andre',
    ],
    'Goupil': ['G2', 'G4', 'G5', 'G6', 'Andre'],
    'Hiphi': ['X', 'Z', 'Y', 'Andre'],
    'Honda': [
        'Accord', 'CR-V', 'CR-Z', 'CRX', 'Civic', 'e', 'e:Ny1', 'Element', 'FR-V', 'HR-V',
        'Insight', 'Integra', 'Jazz', 'Legend', 'Nsx', 'Odyssey', 'Prelude', 'Quintet', 'Ridgeline',
        'S2000', 'Shuttle', 'Stream', 'Andre',
    ],
    'Hongqi': ['E-HS9', 'Andre'],
    'Hummer': ['H1', 'H2', 'H3', 'HX', 'Andre'],
    'Hyundai': [
        'Accent', 'Atos', 'Coupe', 'Elantra', 'Galloper', 'Getz', 'Grand Santa Fe', 'H-1', 'H-100',
        'IONIQ', 'Ioniq 5', 'Ioniq 6', 'Kona', 'Matrix', 'Nexo', 'Pony', 'Santa Fe', 'Sonata',
        'Terracan', 'Trajet', 'Tucson', 'Veloster', 'X35', 'XG', 'i10', 'i20', 'i30', 'i40', 'ix20',
        'ix35', 'ix55', 'Andre',
    ],
    'Infiniti': [
        'FX30D', 'FX35', 'FX37', 'FX45', 'FX50', 'G35', 'G37', 'M35', 'M45', 'Q30', 'Q50 Hybrid',
        'QX56', 'Andre',
    ],
    'Isuzu': ['D-max', 'Trooper', 'Andre'],
    'Iveco': ['3510', 'Daily', 'Andre'],
    'JAC': ['e-JS4', 'Andre'],
    'Jaguar': [
        'E-PACE', 'E-TYPE', 'F-PACE', 'F-TYPE', 'I-PACE', 'S-TYPE', 'X-TYPE', 'XE', 'XF', 'XJ',
        'XJR', 'XJS', 'XK', 'Andre',
    ],
    'Jeep': [
        'Avenger', 'Cherokee', 'Comanche', 'Commander', 'Compass', 'Grand Cherokee', 'J 20',
        'Patriot', 'Renegade', 'Wrangler', 'Gladiator', 'Andre',
    ],
    'Jensen': ['Interceptor', 'Andre'],
    'Kewet': ['Buddy', 'City-Jet 5', 'El-Jet', 'Andre'],
    'Kia': [
        'Besta', 'Carens', 'Carnival', "Cee'd", 'Cerato', 'Clarus', 'Credos', 'E-Niro', 'EV6',
        'Magentis', 'Niro', 'Optima', 'Picanto', 'Pregio', 'Pride', 'ProCeed', 'Rio', 'Sephia',
        'Shuma', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Stonic', 'Venga', 'XCeed', 'Andre',
    ],
    'Koenigsegg': ['CCR', 'Andre'],
    'Lada': ['1200', '1300', '1500', '1600', 'Niva', 'Samara', 'Andre'],
    'Lamborghini': [
        'Aventador', 'Countach', 'Diablo', 'Gallardo', 'Huracan', 'Huracan Spyder', 'LM',
        'Murcielago', 'Urus', 'Andre',
    ],
    'Lancia': [
        'A112', 'Delta', 'Kappa', 'Lybra', 'Musa', 'Phedra', 'Prisma', 'Thema', 'Thesis', 'Y10',
        'Ypsilon', 'Andre',
    ],
    'Lucid': ['Air', 'Andre'],
    'Land Rover': [
        'Defender', 'Discovery', 'Discovery Sport', 'Freelander', 'Range Rover',
        'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar', 'Andre',
    ],
    'Lexus': [
        'CT200h', 'ES', 'GS', 'IS', 'LC', 'LS', 'NX 300h', 'NX 450h', 'RC', 'RC300h', 'RZ', 'RX300',
        'RX400h', 'RX450h', 'SC', 'UX', 'RX500h', 'Andre',
    ],
    'Lincoln': ['Navigator', 'Town Car', 'Andre'],
    'Lotus': ['Elise', 'Europa S', 'Eletre', 'Evora', 'Exige', 'Seven', 'Andre'],
    'MAN': ['TGE', 'eTGE', 'Andre'],
    'Mia Electric': ['mia', 'mia L', 'mia U'],
    'MG': [
        'MG4', 'MG5', 'MG-F', 'EHS', 'MGB', 'Marvel R', 'TF', 'ZS', 'ZS EV', 'mia', 'ZT', 'Andre',
    ],
    'Mini': [
        'Cabrio', 'Clubman', 'Cooper', 'Cooper S', 'Cooper SE', 'Countryman', 'Coupe', 'One',
        'Paceman', 'Roadster', 'Andre',
    ],
    'Maserati': [
        '222', '3200', '3500', 'Biturbo', 'Coupe', 'Ghibli', 'Gran Turismo', 'Indy', 'Levante',
        'MC20', 'Mistral', 'Quattroporte', 'Quattroporte Evoluzzione', 'Spyder', 'GranCabrio',
        'Grecale', 'Andre',
    ],
    'Matra': ['Bagheera', 'Murena', 'Andre'],
    'Maxus': [
        'ev80', 'e-Deliver 3', 'e-Deliver 9', 'Euniq MPV', 'Euniq 5', 'Euniq 6', 'T90 EV', 'MIFA 9',
        'Andre',
    ],
    'Maybach': ['57'],
    'Mazda': [
        '121', '2', '3', '323', '5', '6', '626', '929', 'B 2500 Freestyle Cab', 'B2000', 'B2200',
        'B2600', 'BT-50', 'CX-3', 'CX-5', 'CX-7', 'CX-30', 'CX-60', 'Demio', 'E2000', 'MPV', 'MX-3',
        'MX-30', 'MX-5', 'Premacy', 'RX-2', 'RX-7', 'RX-8', 'Tribute', 'Xedos', 'Andre',
    ],
    'McLaren': ['12C', '570GT', '570S', '675LT', '720S', '765LT', 'Artura', 'Andre'],
    'Mercedes-Benz': [
        '190', 'A-klasse', 'AMG GT', 'AMG GT C', 'AMG GT R', 'AMG GT S', 'B-Klasse', 'C-Klasse',
        'C-Klasse All-Terrain', 'CL', 'CLA', 'CLC', 'CLK', 'CLS', 'Citan', 'eCitan', 'E-Klasse',
        'E-Klasse All-Terrain', 'EQC', 'EQS', 'EQB', 'EQE', 'EQE SUV', 'EQV', 'EQA', 'EQS SUV',
        'GL', 'GLA', 'GLB', 'GLC', 'GLE', 'GLK', 'GLS', 'Geländewagen', 'M-Klasse', 'R-Klasse',
        'S-Klasse', 'SL', 'SLC', 'SLK', 'SLR', 'SLS', 'Sprinter', 'V-Klasse', 'Vaneo', 'Viano',
        'Vito', 'X-Klasse', 'Andre',
    ],
    'Mercury': ['Andre'],
    'Mitsubishi': [
        '3000 gt', 'ASX', 'Carisma', 'Colt', 'Eclipse', 'Eclipse Cross', 'Galant', 'Grandis',
        'L200', 'L300', 'L400', 'Lancer', 'Outlander', 'Pajero', 'Pajero Pinin', 'Pajero Sport',
        'Sapporo', 'Sigma', 'Space Gear', 'Space Runner', 'Space Star', 'Space Star l',
        'Space Wagon', 'i-Miev', 'Andre',
    ],
    'Morgan': ['3-wheeler', '4/4', 'Aero 8', 'Plus 4', 'Plus 8', 'Roadster', 'Andre'],
    'Morris': ['Mini', 'Andre'],
    'Nio': ['ES8', 'EL7', 'ET7', 'ET5'],
    'Nissan': [
        '100 NX', '200 SX', '300 ZX', '370z', 'Almera', 'Ariya', 'Bluebird', 'Cherry', 'Cube',
        'GT-R', 'Interstar', 'Juke', 'King Cab', 'King Van', 'Kubistar', 'Laurel', 'Leaf', 'Maxima',
        'Micra', 'Murano', 'NP300', 'NV200', 'NV250', 'NV300', 'NV400', 'Navara', 'Note',
        'Pathfinder', 'Patrol', 'Pixo', 'Prairie', 'Primastar', 'Primera', 'Pulsar', 'Qashqai',
        'Qashqai +2', 'Serena', 'Skyline', 'Stanza', 'Sunny', 'Terrano', 'Tino', 'Townstar',
        'X-Trail', 'e-NV200',
    ],
    'Nosmoke': ['Original', 'Truckï', 'Andre'],
    'Oldsmobile': ['Custom', 'Cutlass', 'Delta', 'Omega', 'Andre'],
    'Opel': [
        'ADAM', 'Agila', 'Ampera', 'Antara', 'Ascona', 'Astra', 'Calibra', 'Campo', 'Combo',
        'Commodore', 'Corsa', 'Crossland X', 'Frontera', 'GT', 'Grandland', 'Grandland X',
        'Insignia', 'Insignia Country Tourer', 'Kadett', 'Kapitan', 'Manta', 'Meriva', 'Mokka',
        'Monterey', 'Monza', 'Movano', 'Omega', 'Rekord', 'Senator', 'Signum', 'Sintra',
        'Speedster', 'Tigra', 'Vectra', 'Vivaro', 'Zafira', 'Zafira Tourer', 'Andre',
    ],
    'Packard': ['Clipper', 'Andre'],
    'Panther': ['J72', 'Kallista', 'Lima', 'Andre'],
    'Peugeot': [
        '1007', '106', '106 Electric', '107', '108', '2008', '205', '206', '206 CC', '206 SW',
        '207', '207 CC', '207 SW', '208', '3008', '305', '306', '307', '307 CC', '307 SW', '308',
        '308 SW', '309', '4007', '4008', '405', '406', '407', '408', '5008', '505', '508', '605',
        '607', '806', '807', 'Bipper', 'Boxer', 'Export', 'e-Export', 'Partner', 'Partner Electric',
        'RCZ', 'Rifter', 'Traveller', 'iOn', 'Andre',
    ],
    'Piaggio': ['Porter', 'Porter Maxxi', 'Andre'],
    'Plymouth': ['Grand Voyager', 'Roadrunner', 'Voyager', 'Andre'],
    'Polestar': ['1', '2', 'Andre'],
    'Pontiac': ['Bonneville', 'Fiero', 'Firebird', 'Solstice', 'Trans Am', 'Trans Sport', 'Andre'],
    'Porsche': [
        '356', '911', '914', '924', '928', '944', '968', 'Boxster', 'Carrera GT', 'Cayenne',
        'Cayenne Coupe', 'Cayman', 'Macan', 'Panamera', 'Taycan', 'Taycan Cross Turismo',
        'Taycan Sport Turismo', 'Andre',
    ],
    'Radical': ['RXC', 'SR1', 'SR3', 'SR8', 'Andre'],
    'RAM': ['500', '1500', '2500', '3500', '5500', 'Andre'],
    'Renault': [
        '12', '14', '15', '16', '17', '18', '19', '20', '30', '5', 'Avantime', 'C3', 'Captur',
        'Clio', 'Espace', 'Express', 'Fuego', 'Grand Espace', 'Grand Scenic', 'Kadjar', 'Kangoo',
        'Kangoo Electric', 'Kangoo Express', 'Koleos', 'Laguna', 'Master', 'Megane', 'Megane CC',
        'Modus', 'Scenic', 'Talisman', 'Trafic', 'Twingo', 'Twizy', 'Zeo', 'Andre',
    ],
    'Reva': ['Andre'],
    'Rolls-Royce': ['Cullinan', 'Ghost', 'Phantom', 'Silver Shadow', 'Wraith', 'Andre'],
    'Rover': [
        '200-serie', '400-serie', '600-serie', '800-serie', 'Defender', 'Mini', '25', '45', '75',
        'Andre',
    ],
    'Saab': ['9-3', '9-5', '900', '9000', '99', 'Andre'],
    'Santana': ['PS10', 'Andre'],
    'Scion': ['tC', 'xA', 'xB', 'Andre'],
    'SEAT': [
        'Alhambra', 'Altea', 'Arona', 'Arosa', 'Ateca', 'Cordoba', 'Cordoba Vario', 'Ibiza', 'Inca',
        'Leon', 'Leon XP', 'Mii', 'Tarraco', 'Toledo', 'Andre',
    ],
    'Seres': ['3', '5', 'SF5', 'SF7', 'Andre'],
    'Skoda': [
        'Citigo', 'Enyaq', 'Enyaq Coupe RS', 'Fabia', 'Favorit', 'Felicia', 'Forman', 'Kamiq',
        'Karoq', 'Kodiaq', 'Kodiaq Scout', 'Octavia', 'Octavia RS', 'Octavia Scout', 'Pickup',
        'Rapid', 'Rapid Spaceback', 'Roomster', 'Scala', 'Superb', 'Yeti', 'Andre',
    ],
    'Smart': ['Crossblade', 'Forfour', 'Fortwo', 'Roadster', 'Roadster coupe', 'Andre'],
    'SsangYong': [
        'Actyon Sport', 'Family', 'Korando', 'Kyron', 'Musso', 'Rexton', 'Rexton Sports',
        'Rexton W', 'Rodius', 'Tivoli', 'XLV', 'Andre',
    ],
    'Subaru': [
        'B9 Tribeca', 'BRZ', 'Domingo', 'Forester', 'Impreza', 'Justy', 'L-serie', 'Legacy',
        'Levorg', 'Outback', 'Solterra', 'Trezia', 'XV', 'Andre',
    ],
    'Suzuki': [
        'Alto', 'Across', 'Baleno', 'Grand Vitara', 'Ignis', 'Jimny', 'Kizashi', 'Liana', 'SJ',
        'SX4', 'SX4 S-Cross', 'Splash', 'Swift', 'Vitara', 'Wagon R+', 'XL7', 'Andre',
    ],
    'TVR': ['Andre'],
    'Tazzari': ['Andre', 'Zero'],
    'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y', 'Roadster'],
    'Think': ['City', 'Andre'],
    'Toyota': [
        '4-Runner', 'Auris', 'Avensis', 'Avensis Verso', 'Aygo', 'Aygo X', 'bZ4X', 'C-HR', 'Camry',
        'Carina', 'Celica', 'Corolla', 'Corolla Cross', 'Corolla Verso', 'Cressida', 'Crown',
        'Dyna', 'GR Supra', 'GR86', 'GT86', 'HiAce', 'HiClass', 'HiLux', 'Highlander', 'IQ',
        'Lander Cruiser', 'MR2', 'Mirai', 'Picnic', 'Previa', 'Prius', 'Prius Plug-in Hybrid',
        'Prius+ Seven', 'Proace', 'Proace City', 'Proace Verso', 'RAV4', 'Sienna', 'Starlet',
        'Supra', 'Tacoma', 'Tercel', 'Tundra', 'Urban Cruiser', 'Verso', 'Verso-S', 'Yaris',
        'Yaris Cross', 'Yaris Verso', 'GR Yaris', 'Andre',
    ],
    'Triumph': ['Spitfire', 'TR7', 'Andre'],
    'Volkswagen': [
        'Amarok', 'Arteon', 'Beetle', 'Boble (gammel type)', 'Bora', 'Caddy', 'Caddy Alltrack',
        'Caddy Maxi', 'Caravelle', 'Corrado', 'Crafter', 'Derby', 'Eos', 'Golf', 'Golf Alltrack',
        'Golf Cross', 'Golf Plus', 'Golf Sportsvan', 'ID. Buzz', 'ID.3', 'ID.4', 'ID.4 GTX', 'ID.5',
        'ID.5 GTX', 'ID.7', 'Jetta', 'K 70', 'Kombi', 'LT', 'Lupo', 'Multivan', 'Passat',
        'Passat Alltrack', 'Passat CC', 'Phaeton', 'Polo', 'Polo Cross', 'Santana', 'Scirocco',
        'Sharan', 'T-Cross', 'T-Roc', 'Taro', 'Tiguan', 'Tiguan Allspace', 'Touareg', 'Touran',
        'Transporter', 'UP!', 'Variant', 'Vento', 'Andre',
    ],
    'Volvo': [
        '142', '144', '145', '164', '240', '242', '244', '245', '264', '265', '340', '343', '345',
        '360', '440', '460', '480', '744', '740', '745', '760', '780', '850', '940', '960',
        'Amazon', 'C30', 'C40', 'C70', 'Duett', 'P1800', 'PV', 'S40', 'S60', 'S60 Cross Country',
        'S70', 'S80', 'S90', 'V40', 'V40 Cross Country', 'V50', 'V60', 'V60 Cross Country', 'V70',
        'V90', 'V90 Cross Country', 'XC40', 'XC60', 'XC70', 'XC90', 'Andre',
    ],
    'Voyah': ['FREE', 'Andre'],
    'Wiesmann': ['Andre', 'GT MF4', 'GT MF5', 'MF3', 'MF30', 'Roadster MF4', 'Roadster MF5'],
    'XPeng': ['G3', 'G3i', 'G9', 'P5', 'P7', 'Andre'],
    'ZD': ['D1', 'Andre'],
    'Andre': ['Andre'],
} as const satisfies Record<CarBrand, readonly string[]>;

/** The models listed for a brand — `[]` for a brand that is not in CAR_BRAND_OPTIONS. */
export const carModelsFor = (brand: string): readonly string[] =>
    (CAR_MODELS_BY_BRAND as Record<string, readonly string[]>)[brand] ?? [];

/**
 * brand (category: Car, vehicleType: campingvogn) — 135 entries. Optional. Caravan models are free
 * text.
 */
export const CARAVAN_BRAND_OPTIONS = [
    'Adria', 'Ahorn', 'Airstream', 'Atlas', 'Autostar', 'Basoglu', 'Bavaria', 'Bela', 'Benimar',
    'Bjølseth', 'Bravia', 'Bürstner', 'CI', 'CS', 'Cabby', 'Camp_Let', 'Carado', 'Caravelair',
    'Carbon Tear', 'Carthago', 'Cavalier', 'Challenger', 'Chausson', 'Chevrolet', 'Clever',
    'Combi-Camp', 'Concorde', 'Crawler', 'DAF', 'Decamp', 'Dethleffs', 'Derubis', 'Dream',
    'Dreamer', 'Eifelland', 'Elnagh', 'Esterel', 'Eura Mobil', 'FR-Mobil', 'Fiat awning', 'Fendt',
    'Fiat', 'Flair', 'Fleetwood', 'Fleurette', 'Ford', 'Frankia', 'GG', 'Gigant', 'Giottiline',
    'Globe-Traveller', 'Globecar', 'Glucksmobil', 'Grau', 'Gulfstream', 'Hero Camper', 'Hino',
    'Hobby', 'Holiday Rambler', 'Home-car Caravans', 'Hymer', 'Ilusion', 'Itineo', 'KABE',
    'Karmann', 'Kentucky Camp', 'Kip', 'Knaus', 'Kulba', 'LMC', 'LMC/Münsterland', 'La Strada',
    'Laika', 'Le Voyageur', 'Lifestyle Camper', 'Malibu', 'Mclouis', 'Mege Mobile', 'Mercedes-Benz',
    'Miller', 'Mink', 'Mirage', 'Mobil Traveller', 'Mobilvetta', 'Monaco', 'Morelo', 'Muflon',
    'Neo Traveller', 'Niesmann-Bischoff', 'Nissan', 'Nordic', 'Norgeshengern', 'Orangecamp',
    'P.L.A', 'Peugeot', 'Phoenix', 'Pilote', 'Polar', 'Poletta', 'Pøssl', 'RMB', 'Raidhoo Campers',
    'Rapido', 'Respo', 'Rimor', 'Riviera', 'Roadcar', 'Rockwood', 'Roller Team', 'Savsjø', 'Scania',
    'Sharky', 'SMV', 'Solifer', 'Sprite', 'Sterckeman', 'Sun Living', 'Sunlight', 'Swift',
    'T.E. Caravan', 'Tabbert', 'Tec', 'Tourne', 'Triple E', 'Troll', 'VANTourer', 'Volkswagen',
    'WINGAMM', 'Weinsberg', 'Weippert', 'Westfalia', 'Wilk', 'Willerby', 'Winnebago', 'Other',
] as const;
export type CaravanBrand = (typeof CARAVAN_BRAND_OPTIONS)[number];

/**
 * brand (category: Car, vehicleType: bobil) — 135 entries. Optional, and the same list as the
 * caravan form. Motorhome models are free text.
 */
export const MOTORHOME_BRAND_OPTIONS = CARAVAN_BRAND_OPTIONS;
export type MotorhomeBrand = (typeof MOTORHOME_BRAND_OPTIONS)[number];

/**
 * brand (category: Boat) — 799 entries. Optional. Boat models are free text, and the source list
 * has no brand starting G-L — those go under `Andre`.
 */
export const BOAT_BRAND_OPTIONS = [
    '5,5 meter', '8 meter', 'AB Inflatables', 'AB Yacht', 'Adonis', 'AGA', 'AL', 'AMT', 'Absolute',
    'Accent', 'Achilles', 'Acquaviva', 'Adrenaline', 'Adriatic', 'Adventurer', 'Aermarine', 'Agder',
    'Aicon', 'Airon Marine', 'Airship', 'Airship Ribs', 'Akerø', 'Albatross', 'Albin', 'Alfa',
    'Aliboats', 'Alicraft', 'Alloycraft', 'Allures', 'Almarcraft', 'Alo', 'Alpha Boat',
    'AluVenture', 'Alubat', 'Alucraft', 'Alufish', 'Alukin', 'AluMarin', 'Alunaut', 'Alunautic',
    'Alutec', 'Ancas Queen', 'Andunge', 'Andy', 'Angler', 'Antaris', 'Anytec', 'Aphrodite',
    'Apollo', 'Aqua', 'Aquamot', 'Aquador', 'Aqualela', 'Aquamar', 'Aquamarine', 'Aquapro',
    'Aquaquad', 'Aquaquick', 'Aquarius', 'Aquaspirit', 'Aquatron', 'Aquid', 'Archambault', 'Arcona',
    'Arctic', 'Arctic Blue', 'Ardea', 'Arendalsnekke', 'Argo', 'Arimar', 'Arksund', 'Armor',
    'Arronet', 'Artekno', 'Artic', 'Arvor', 'Askeladden', 'Aspen', 'Astondoa', 'Athena',
    'Athena 38', 'Atlantic', 'Atlantic Marine', 'Atlantis', 'Atomix', 'Australian high performance',
    'Avance', 'Avanti', 'Aventura', 'Avon', 'Awtish', 'Axopar', 'Azimut', 'Azure', 'Azzurro',
    'BAJA', 'BB', 'Belassi', 'Bente', 'BIC', 'BMB', 'BOWI Serai', 'BRIG', 'BRP', 'BWA', 'Bakke',
    'Bali', 'Ballistic', 'Balt', 'Baltic', 'Bandholm', 'Banner', 'Barcon', 'Baretta', 'Barracuda',
    'Baug', 'Bavaria', 'Bayliner', 'Becker', 'Bell', 'Bella', 'Benelli', 'Beneteau', 'Bennington',
    'Berika', 'Berkut', 'Bertram', 'BestMarin', 'Bestyear', 'Bever', 'Biam', 'Bianca', 'Birchwood',
    'Blackwater', 'Black Fin', 'Blesser', 'Blusail', 'Blue Spirit', 'Bluesea', 'Boheme', 'Bolero',
    'Bombard', 'Bonanza', 'Boston Whaler', 'Bostrøm', 'Bowrider', 'Brabus Marine', 'Braveboat',
    'Brenta', 'Brioni', 'Brizo Yachts', 'Broom', 'Bryant', 'Bryza', 'Bumerang', 'Buster',
    'Båtsmann', 'C&C', 'CAP FERRET', 'CB', 'CDE', 'CR', 'CRN', 'Calypso', 'Camoline', 'Campion',
    'Canmar', 'Cantieri di Sarnico', 'Capelli', 'Carat', 'Caravelle', 'Caribe', 'Carver',
    'Castello Marine', 'Catalina', 'Cayenne', 'Cenit', 'Century', 'Challenger', 'Champion',
    'Chaparral', 'Checkmate', 'Chris Craft', 'Cigarette', 'Ciljan', 'Cleopatra', 'Clipper',
    'Coast Liner', 'CoastMaster', 'Coaster', 'Cobalt', 'Cobra', 'Cobrey', 'Colin Archer', 'Colombo',
    'Comet', 'Comfort', 'Comfortina', 'Compass', 'Concord', 'Contessa', 'Contest', 'Contrast',
    'Conqubin', 'Cooper', 'Cormate', 'Coronet', 'Corvette', 'Coverline', 'Cranchi', 'Crescent',
    'Crownline', 'Cruiser', 'Cruisers', 'Custom Line', 'Cutwater', 'Cyber 370', 'Dacapo',
    'Dalla Pieta', 'Dateline', 'DeFever', 'Degerø', 'Dehler', 'Dell Quay Dory', 'Delphia', 'Delta',
    'Derubis Yachts', 'Diana', 'Discovery', 'Diva', 'Dixie', 'Dolmøy', 'Dolphin', 'Dolvik',
    'Dominant', 'Donzi', 'Doral', 'Doriff', 'Drabant', 'Draco', 'Drago', 'Dragonfly', 'Drake',
    'Drive', 'Dromeas', 'Dromedille', 'Dsp', 'Dufour', 'Duramar', 'Dynamic', 'Ebbtide',
    'Edge Water', 'Eikeli', 'Elan', 'Elling', 'Elwaro', 'Emili', 'Endourance', 'Enes', 'Eolo',
    'Epoca', 'Etap', 'Euro Yacht', 'Eurocraft', 'Europajolle', 'Eurosport', 'Evada', 'Excedo',
    'Excess catamarans', 'Explorer', 'FM', 'FUN', 'Fabola', 'Faeton', 'Fagitta', 'Fairline',
    'Falcon', 'Fantasi', 'Farr', 'Fast CAB', 'Faster', 'Faurby', 'Feeling', 'Femundbåt', 'Fenix',
    'Ferretti', 'Fevik', 'Fiart', 'Finessa', 'Finncamp', 'Finngulf', 'Finnmaster', 'Finnsailer',
    'Finnsport', 'Firling', 'First', 'First Class 8', 'Fiskeskøyte', 'Fiord', 'Fjord Terne',
    'Fjord boats', 'Fjordling', 'Flem', 'Fleming', 'Fletcher', 'Flipper', 'Folla', 'Forbina',
    'Forgus', 'Formosa', 'Formula', 'Formula Watercraft', 'Fortego', 'Fountain', 'Fountaine Pajot',
    'Fourwinns', 'Fram', 'Frauscher', 'Freedom', 'Freeman', 'Frers & Cibil', 'Frib', 'Friendship',
    'Fun-Yak', 'Furuholmen', 'Færing', 'Måløy', 'Mamba', 'Mantra', 'Marine Technology Inc',
    'MAR-CO', 'Marex', 'Mariah', 'Marieholm', 'Maril', 'Marina', 'Mariner', 'Marino', 'Marion',
    'Maritimo', 'Marlin', 'Marquis', 'Mascot', 'Master', 'Mastercraft', 'Matrix', 'Maxi', 'Maxum',
    'Maxus', 'Mazury', 'Mekling', 'Melges', 'Menken Maritiem', 'Mercury', 'Meridian Yachts',
    'Mery Nautic', 'Micore', 'Mikkel', 'Milia', 'Millenium', 'Minor', 'Mirage', 'Mixer', 'Modesty',
    'Modius', 'Momentum', 'Monaco', 'Monark', 'Monterey', 'Moody', 'Morgan', 'Mosquito', 'Motiva',
    'Motor Scoop', 'Musling', 'Mustang', 'Myra', 'Møn', 'Mørebas', 'Mørejet', 'NB', 'NEEL',
    'NabCat', 'NabWork', 'Nacra', 'Najad', 'Narwhal', 'Nauta', 'Nauticat', 'Nautico', 'Nautor',
    'Nautus', 'NAVAN', 'Naver', 'Navette', 'Neptim', 'Neptunkrysser', 'Neptunus', 'Nessy',
    'NewClassic', 'NF', 'Nicholson', 'Nidelv', 'Nilsen', 'Nimbus', 'Nimo', 'Nisami Rib', 'Nitra',
    'Nor Sea', 'Nor Star', 'Nor-Dan', 'Nor-Tech', 'Nordic Season', 'NorPlast', 'NorTech',
    'Noratlantis', 'Norbas', 'Norbelle', 'Norbåt', 'Norcraft', 'Nord West', 'NordStar',
    'Nordic Marine', 'Nordic Ocean Craft', 'Nordic Star', 'Nordisk folkebåt', 'Nordkapp',
    'Nordship', 'Norfun', 'Norlin', 'Norline', 'Norman', 'Norrib', 'Norsafe', 'North Atlantic Rib',
    'Northman', 'North Pacific', 'North ribs', 'Northmaster', 'NorthStar', 'Nottoy', 'Nova',
    'NuovaJolly', 'Novurania', 'Nymar', 'OX', 'Obsession', 'Ocean Alexander', 'OceanMarin',
    'Oceancraft', 'Oceanfarer', 'Oceanis', 'Oceanmaster', 'Oceanrunner', 'Ockelbo', 'Ocqueteau',
    'Olson 88', 'Olympic', 'Ombrine', 'Omega', 'Optima', 'Orrskär', 'Oselvar', 'Otasport', 'Oyster',
    'Pacific Craft', 'Paijan', 'Pakri', 'Paragon', 'Paramount Powerboats', 'Parent', 'Partizan',
    'Pearlsea', 'Pegazus', 'Pershing', 'Pettersson', 'Piet Hein Sloep', 'Pilot', 'Pioner',
    'Plattgatter', 'Polar', 'Polarcirkel', 'Polaris', 'Polarkraft', 'Pogo', 'Polo', 'Poseidon',
    'PowerQuest', 'Powercraft', 'Predator', 'Prestige', 'Princess', 'Pro Rib', 'Pro-Line',
    'ProWorker', 'Pronavia', 'Protagon', 'Protector', 'Puma', 'Pursuit', 'Quarken', 'Quicksilver',
    'RIS', 'Racemaster', 'Racing Sailboats', 'Rafnar', 'Ram-Marine', 'Ramin', 'Ran Craft', 'Rana',
    'Rand', 'Ranger', 'Ranger Tugs', 'Ranieri', 'Rascala', 'Rasmus', 'Ravage', 'Real', 'Realcraft',
    'Regal', 'Reinell', 'Remus', 'Revenger', 'Rhea', 'Rib Limited', 'Ribcraft', 'Ribeye', 'Ridas',
    'Rinker', 'Risør', 'Riva', 'Rival', 'Rivena Yachts', 'River', 'Riviera', 'RM-Yachts', 'Robalo',
    'Rocad', 'Rodman', 'Rondo', 'Row', 'Royal Cruiser', 'Royal Marine', 'RS Sailing', 'R-boats',
    'Rubenetti', 'Runn37', 'Rupert', 'Rush', 'Ryck', 'Ryds', 'RW', 'SACS', 'SK', 'SL', 'SUN',
    'Safir', 'Saffier Yachts', 'Safter', 'Saga', 'Sagen', 'Sagitta', 'Salman Theri', 'Salona',
    'Salpa', 'Sand', 'Sandström', 'Sandstø', 'Sandtangen', 'Sandvik', 'Sandøy', 'Sargo', 'Saver',
    'Saxdor', 'Saxe', 'Scampi', 'Scand', 'Scandica', 'Scandinaval', 'Scandinavien', 'Scanmar',
    'Scanner', 'Scarab', 'Scarani', 'Schaefer Yachts', 'Scorpion', 'Scout', 'SeasAll', 'Sea Finn',
    'Sea Hawk', 'Sea Jeep', 'Sea Master', 'Sea Pro', 'Sea Queen', 'Sea Ray', 'Sea Star', 'SeaDan',
    'SeaDoo', 'Sea Force One', 'SeaHunter', 'SeaRider', 'SeaWave', 'Seabird', 'SeaBoy', 'Seabraker',
    'Seaco', 'Skagerak', 'Skarpnes', 'Skarsvåg', 'Skater', 'Skibsplast', 'Skilsø', 'Skipper',
    'Skipperyachts', 'Skorgenes', 'Skøyte', 'Smart Rib', 'Smartliner', 'Smiling', 'Smuggler',
    'Snipe', 'Solaris', 'Soling', 'Sollux', 'Solvik', 'Spirit', 'Spornes', 'Sportique', 'Spoty',
    'Sprint', 'SPX Rib', 'Starcraft', 'Starfisher', 'Statesman', 'Steady', 'Stigfjord', 'Sting',
    'Stingher', 'Stingray', 'Storebro', 'Storm', 'Stormway', 'Stormy', 'Storø', 'Strandebarmer',
    'Stråholmen', 'Strana', 'Strømøy Rib', 'Style', 'SugarSand', 'Summer Dreams', 'Summer Family',
    'Summersport', 'Sun Fast', 'Sun Marine', 'Sun Odyssey', 'Sun Quest', 'Sun Tracker', 'Sunbeam',
    'Sunbird', 'Sunchaser', 'Sunline', 'Sunrider', 'Sunsation', 'Sunseeker', 'Sunwind', 'Suomi',
    'SurPlus', 'Sur Marine', 'Suvi', 'Suzumar', 'Swan', 'Swede', 'SwedeStar', 'Sweden Yachts',
    'Sørlandssnekka', 'TB', 'TG-Boat', 'TP Marine', 'Tahoe', 'Takacat', 'Tango', 'Targo', 'Tartan',
    'Tayana', 'TD Power', 'Teal', 'Technohull', 'Technorib', 'TEKNOMAR', 'Terhi', 'Tethys Yachts',
    'Tetis', 'Thunderbird', 'Tiara', 'Tiger Marine', 'Tiwal', 'Tobias', 'Topaz', 'Topcat',
    'Tornado', 'Toy', 'Tracker', 'Trader', 'Trapper', 'Trawler', 'Tresfjord', 'Trinella',
    'Trintella', 'Trio', 'Tristan', 'Triton', 'Troll', 'Tromøy', 'Trophy', "Trønder'n", 'TS Boats',
    'Tullio Abbate', 'Tune-jolle', 'Tustna', 'Twostar', 'UMS', 'UMS Boats', 'Uniesse', 'Unique',
    'Uttern', 'Vaagen', 'Valiant', 'Van Der Heijden', 'Venus', 'VENTUM', 'Vermøy', 'Vernøy',
    'Verøy', 'Veslefrikk', 'Vest', 'Vestfjord', 'Viggo', 'Vikfjord', 'Viking', 'Viknes',
    'Viko Yachts', 'Viksfjord', 'Viksund', 'Vindø', 'Vinstrabåten', 'Viper', 'Vira', 'Virus',
    'Vista', 'Walker Bay', 'Wally', 'Wasa', 'Waszp', 'Water Fun', 'Watercraft', 'Waterwish',
    'Wauquies', 'Wayfarer', 'Wellcraft', 'Wesling', 'West', 'Westbas', 'Westcruiser', 'Wester',
    'Westerly', 'Westfjord', 'Westline', 'WESTPLAST', 'Wharram', 'White Shark', 'Whitehouse',
    'Wiking', 'Williams', 'Willing', 'Windy', 'Winga', 'Winrace', 'With', 'X-Yachts', 'XO',
    'XShore', 'XS Ribs', 'Yam', 'Yamaha', 'Yamarin', 'Yngling', 'ZAR', 'Zebec', 'Zee Marine',
    'Zephyr', 'Zitarra', 'Zodiac', 'Zulu Marine', 'Ribtech', 'Øien', 'Ørnvik', 'Årø', 'Andre',
] as const;
export type BoatBrand = (typeof BOAT_BRAND_OPTIONS)[number];

/**
 * brand (category: Motorcycle) — 263 entries. Optional, and shared by motorsykkel, moped, ATV and
 * snøscooter. MC models are free text.
 */
export const MC_BRAND_OPTIONS = [
    '4Speed', '4W-Moto', 'AIE', 'AIMA', 'AJP', 'AJS', 'ARGO', 'ATZ', 'Access', 'Adiva', 'Adly',
    'Aenon', 'Aeon', 'Aero', 'Agirra', 'Aixam', 'Allroad', 'Alpina', 'Altina',
    'American Iron Horse', 'Andre', 'Apex', 'Aprilia', 'Arctic-cat', 'Ariel', 'Atala', 'Atex',
    'BMW', 'BSA', 'Bajaj', 'Baotian', 'Barossa', 'Benelli', 'Benghe', 'Beta', 'Big Dog', 'Bimota',
    'Bluroc', 'Bombardier', 'Boss Hoss', 'Bourget', 'Brudeli', 'Buell', 'Bullit', 'Bultaco',
    'Bunker Trike', 'CFMOTO', 'CPI', 'Cagiva', 'Cake', 'Can-Am', 'Casalini', 'Cectek', 'Chatenet',
    'Citroen', 'Classic', 'Club Cadet', 'Cobra', 'Comarth', 'Corvus', 'Crescent', 'DTV Shredder',
    'Daelim', 'Dayun', 'Derbi', 'Di Blasi', 'Dinli', 'Ducati', 'E-ton', 'EMC', 'Electric Motion',
    'Eli Zero', 'Elo', 'Enduro', 'Energica', 'Estrima', 'Euroscooter', 'Evoride', 'Eznen', 'F7',
    'FH', 'FYM', 'Fantic', 'Furia', 'Gamax', 'Garelli', 'GasGas', 'Generic', 'Gilera', 'Goes',
    'Govecs', 'Hammer', 'Hanway', 'Harley-Davidson', 'Hecht', 'Hero', 'Highland', 'Hisun', 'Honda',
    'Hooper', 'Horwin', 'Husaberg', 'Husqvarna', 'Hyosung', 'INDIAN', 'Iso Milano', 'Italjet',
    'JCB', 'Jawa/CZ', 'Jinling', 'John Deere', 'Jonway', 'Jotagas', 'Junak', 'KTM', 'Kainuo',
    'Kawasaki', 'Kayo', 'Kazuma', 'Keeway', 'Kinroad', 'Knievel Cycles', 'Kreidler', 'Kubota',
    'Kudaki', 'Kymco', 'LMX', 'Lambretta', 'Lauge Jensen', 'Laverda', 'Lem', 'Lifan', 'Ligier',
    'Lingben', 'Linhai', 'Loncin', 'Longjia', 'Lvneng', 'Lynx', 'MEV', 'MGB', 'MV Agusta', 'MZ',
    'Mademoto', 'Malaguti', 'Mancini', 'Maxgass', 'Maxus', 'Mega', 'Megelli', 'Meijs', 'Microcar',
    'Mikilon', 'Mobelli', 'Moden', 'Mondial', 'Moto Guzzi', 'Moto Morini Corsarino', 'Moto Zeta',
    'MotoNordic', 'MotorMoro', 'Motorbike', 'Motorhispania', 'Motrac', 'NIU', 'NSU', 'Norton',
    'Nzita', 'Ockelbo', 'Odes', 'Opel', 'Oset', 'Ossa', 'Panthera', 'Paoletti', 'Paxster',
    'Peugeot', 'Pgo', 'Piaggio', 'Pioneer', 'Pitpro', 'Polaris', 'Proffy', 'Puch', 'QINGQI',
    'QJ Motor', 'Qooder', 'Qroad', 'Quaddy', 'Quadro', 'Quark', 'RAM', 'RGNT', 'Redline',
    'Regal Raptor', 'Rieju', 'Romet', 'Royal Enfield', 'SMC', 'SWM', 'SYM', 'Sachs', 'Saxon',
    'Scorpa', 'Secma', 'Segway', 'Senda', 'Sherco', 'Silence', 'Simson', 'Skandic', 'Ski-doo',
    'Skyteam', 'Somoto', 'Sonik', 'Starway', 'Streetsmart', 'Super Moto', 'Super Soco', 'Sur Ron',
    'Suzuki', 'TGB', 'TM', 'TRS Motorcycles', 'Talaria', 'Taotao', 'Tazzari', 'Tempo', 'Ten7',
    'Thunder by City Wheels', 'Thundercat', 'Tinger', 'Tms', 'Today Sunshine', 'Tomos', 'Torrot',
    'Triumph', 'Tromox', 'URBET', 'Ural', 'V3', 'V8 Choppers', 'VERTIGO', 'VGA', 'VOGE', 'Vectra',
    'Veli', 'Vespa', 'Viarelli', 'Victory', 'X-PRO', 'XEL', 'XWAY', 'YOYO XEV', 'Yadea', 'Yamaha',
    'Yamoto', 'Yiying', 'Zero', 'Znen', 'Zontes', 'Zundapp', 'Others',
] as const;
export type McBrand = (typeof MC_BRAND_OPTIONS)[number];

/**
 * brand (category: Electronics) — 10 entries. Suggestions only — the field is free text (max 100)
 * and accepts anything.
 */
export const ELECTRONICS_BRAND_OPTIONS = [
    'Apple', 'Sony', 'Samsung', 'Xiaomi', 'HP', 'Lenovo', 'Asus', 'Acer', 'Microsoft', 'Dell',
] as const;
export type ElectronicsBrand = (typeof ELECTRONICS_BRAND_OPTIONS)[number];

/**
 * brand (category: Furniture) — 7 entries. Suggestions only — the field is free text (max 100) and
 * accepts anything.
 */
export const FURNITURE_BRAND_OPTIONS = [
    'Ikea', 'Samsung', 'LG', 'Sony', 'Artwood', 'Saxo Living', 'Englesson',
] as const;
export type FurnitureBrand = (typeof FURNITURE_BRAND_OPTIONS)[number];

/**
 * brand (category: Clothing) — 13 entries. Suggestions only — the field is free text (max 100) and
 * accepts anything.
 */
export const CLOTHING_BRAND_OPTIONS = [
    'Adidas', 'Nike', 'Gant', 'Holzweiler', 'Levis', 'Fila', 'Hugo Boss', 'Line of Oslo',
    'Valentino', 'Armani', 'Les Deux', 'Diesel', 'Ganni',
] as const;
export type ClothingBrand = (typeof CLOTHING_BRAND_OPTIONS)[number];

