param(
  [string]$Domain = "",
  [string]$CertPassword = "localdevcert"
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir
$certDir = Join-Path $repoRoot "docker/nginx/certs"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  throw "Docker is required. Install Docker Desktop first."
}

New-Item -ItemType Directory -Force -Path $certDir | Out-Null

$friendlyName = "backend-mongoose-local-dev"
$dnsNames = @("localhost")
if ($Domain.Trim()) {
  $dnsNames += $Domain.Trim()
}

# Replace old certs generated by this project.
$old = Get-ChildItem Cert:\CurrentUser\My | Where-Object { $_.FriendlyName -eq $friendlyName }
foreach ($cert in $old) {
  Remove-Item -Path ("Cert:\CurrentUser\My\" + $cert.Thumbprint) -Force
}

$cert = New-SelfSignedCertificate `
  -DnsName $dnsNames `
  -CertStoreLocation "Cert:\CurrentUser\My" `
  -FriendlyName $friendlyName `
  -NotAfter (Get-Date).AddYears(3) `
  -KeyAlgorithm RSA `
  -KeyLength 2048 `
  -HashAlgorithm SHA256 `
  -KeyExportPolicy Exportable

$pfxPath = Join-Path $certDir "dev-local.pfx"
$cerPath = Join-Path $certDir "dev-local.cer"
$crtPath = Join-Path $certDir "localhost.crt"
$keyPath = Join-Path $certDir "localhost.key"
$securePassword = ConvertTo-SecureString -String $CertPassword -AsPlainText -Force

Export-PfxCertificate -Cert $cert -FilePath $pfxPath -Password $securePassword | Out-Null
Export-Certificate -Cert $cert -FilePath $cerPath | Out-Null

# Trust cert for current user (no admin required).
Import-Certificate -FilePath $cerPath -CertStoreLocation "Cert:\CurrentUser\Root" | Out-Null
Import-Certificate -FilePath $cerPath -CertStoreLocation "Cert:\CurrentUser\TrustedPeople" | Out-Null

$dockerCertDir = $certDir -replace "\\", "/"
$extractCmd = @(
  "apk add --no-cache openssl >/dev/null",
  "openssl pkcs12 -in /certs/dev-local.pfx -clcerts -nokeys -out /certs/localhost.crt -passin pass:$CertPassword",
  "openssl pkcs12 -in /certs/dev-local.pfx -nocerts -nodes -out /certs/localhost.key -passin pass:$CertPassword",
  "chmod 600 /certs/localhost.key"
) -join " && "

docker run --rm -v "${dockerCertDir}:/certs" alpine:3.20 sh -lc "$extractCmd" | Out-Null

if (-not (Test-Path $crtPath) -or -not (Test-Path $keyPath)) {
  throw "Failed to generate localhost.crt/localhost.key."
}

Remove-Item $pfxPath -Force
Remove-Item $cerPath -Force

if ($Domain.Trim()) {
  Write-Host "HTTPS local cert is ready for localhost and $Domain"
  Write-Host "If $Domain does not resolve on your machine, add a hosts file entry to 127.0.0.1."
} else {
  Write-Host "HTTPS local cert is ready for localhost"
}
Write-Host "Next: docker compose up -d --build"
