import type z from 'zod';

import { boatSchema } from './boat.schema';
import { carCategorySchema } from './car.schema';
import { jobSchema } from './job.schema';
import { motorcycleSchema } from './motorcycle.schema';
import { propertySchema } from './property.schema';
import {
    bikeSchema,
    bookSchema,
    clothingSchema,
    electronicsSchema,
    furnitureSchema,
    sellxSchema,
} from './simple.schema';

/** Slugs generated by `seeds/categories.seed.ts`. */
export const PRODUCT_CATEGORY_SLUGS = [
    'sellx',
    'property',
    'car',
    'boat',
    'motorcycle',
    'bike',
    'job',
    'electronics',
    'book',
    'furniture',
    'clothing',
] as const;

export type ProductCategorySlug = (typeof PRODUCT_CATEGORY_SLUGS)[number];

/**
 * One schema per category, used for both create and update: the spec's
 * `(Required)` fields are enforced on either path, so an edit submits a
 * complete listing rather than a partial patch.
 */
export const PRODUCT_SCHEMAS: Record<ProductCategorySlug, z.ZodType> = {
    sellx: sellxSchema,
    property: propertySchema,
    car: carCategorySchema,
    boat: boatSchema,
    motorcycle: motorcycleSchema,
    bike: bikeSchema,
    job: jobSchema,
    electronics: electronicsSchema,
    book: bookSchema,
    furniture: furnitureSchema,
    clothing: clothingSchema,
};

/**
 * Categories added later by an admin have no bespoke form, so they fall back to
 * the SellX schema — the same fallback `filter-options.service.ts` uses.
 */
export const getProductSchema = (categorySlug: string): z.ZodType =>
    PRODUCT_SCHEMAS[categorySlug as ProductCategorySlug] ?? PRODUCT_SCHEMAS.sellx;
